# Generated by Django 2.2 on 2023-05-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20230526_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='min_quantity',
        ),
        migrations.AddField(
            model_name='price',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('code',), name='payment_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('stripe_id',), name='payment_stripe_id_unique'),
        ),
    ]
