# Generated by Django 2.2 on 2023-06-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20230529_1313'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='payment_code_unique',
        ),
        migrations.RemoveConstraint(
            model_name='price',
            name='payment_stripe_id_unique',
        ),
        migrations.AlterField(
            model_name='price',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
