# Generated by Django 2.2 on 2023-06-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20230601_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
