# Generated by Django 2.2 on 2023-06-07 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_product_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='billing_period',
            field=models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], help_text='For "Recurring" price type only', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='payment.Product'),
        ),
    ]
