# Generated by Django 2.2 on 2023-08-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20230803_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='is_active',
        ),
    ]
