# Generated by Django 2.2 on 2023-08-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_price_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='Used to identify the product. Available values: "fractionalcoo", "premium", "unlimited"', max_length=100, null=True, unique=True),
        ),
    ]
