# Generated by Django 2.2 on 2024-03-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20230818_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('inactive', 'inactive')], help_text='"Archived" status allows only update, "inactive" disables the price', max_length=255),
        ),
    ]
