# Generated by Django 2.2 on 2023-11-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_auto_20230505_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiprompt',
            name='model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('gpt-4-1106-preview', 'gpt-4-turbo-preview'), ('gpt-4', 'gpt-4')], default='gpt-3.5-turbo', max_length=200),
        ),
    ]
