# Generated by Django 2.2.7 on 2020-01-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_slackauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAuth',
        ),
        migrations.DeleteModel(
            name='SlackAuth',
        ),
    ]
