# Generated by Django 2.2 on 2023-10-25 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pneumatic_backend.generics.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_auto_20200113_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('access_token', models.CharField(max_length=3000)),
                ('refresh_token', models.CharField(max_length=3000)),
                ('expires_in', models.PositiveIntegerField(help_text='Seconds before expiration access_token')),
                ('source', models.CharField(choices=[('email', 'email'), ('microsoft', 'microsoft'), ('google', 'google')], max_length=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(pneumatic_backend.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='accesstoken',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('user_id', 'source'), name='auth_access_token_user_unique'),
        ),
    ]
