# Generated by Django 2.2 on 2023-08-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_price_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('inactive', 'inactive')], default=False, help_text='"Archived" status allows only update, "inactive" disables the price', max_length=255),
        ),
        migrations.AlterField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=False, help_text='False if the price is no longer available'),
        ),
        migrations.AlterField(
            model_name='price',
            name='max_quantity',
            field=models.PositiveIntegerField(help_text='Limit the maximum quantity to buy. You can specify a value up to 10000'),
        ),
        migrations.AlterField(
            model_name='price',
            name='min_quantity',
            field=models.PositiveIntegerField(help_text='Minimum quantity, must be less then the "max_quantity"'),
        ),
        migrations.RunSQL("""
            UPDATE payment_price
            SET status = (
              CASE
                WHEN is_active IS TRUE THEN 'active'
                ELSE 'inactive'
              END
            )
        """)
    ]
