# pipenv commands must not be use in entry phrase because
# "entry: pipenv run <command>" much slower than "entry: python -m <command>.__main__"
default_stages: [commit]
default_language_version:
  python: python3.7
repos:
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      types: [python]
      language: system
      entry: ruff check --fix

  - repo: local
    hooks:
      - id: py_codestyle
        name: py_codestyle
        types: [python]
        language: system
        entry: pycodestyle src --config=codestyle.ini
        args:
          - src/
          - --config=codestyle.ini
        exclude: 'migrations|'
