[tool.poetry]
name = "pneumatic-backend"
version = "0.1.0"
description = ""
authors = ["azat.zakirov <zakirmalay@gmail.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "~3.12"
django = "5.2.17"
djangorestframework = "3.16.1"
requests = "2.32.5"
django-configurations = "2.5.1"
django-extensions = "4.1"
psycopg2-binary = "2.9.11"
gunicorn = "23.0.0"
whitenoise = "6.11.0"
django-cors-headers = "4.9.0"
djangorestframework-simplejwt = "5.5.1"
django-json-widget = "2.1.1"
django-filter = "25.2"
slackclient = "2.6.2"
analytics-python = "1.2.9"
django-celery-beat = "2.9.0"
django-redis = "6.0.0"
user-agents = "^2.2.0"
django-tinymce = "4.1.0"
celery = "5.6.3"
channels = "4.3.2"
uvloop = [{version = "0.22.1", platform = 'darwin'}, {version = "0.22.1", platform = 'linux'},]
httptools = "0.7.1"
uvicorn = "0.38.0"
uvicorn-worker = "0.4.0"
channels-redis = "4.3.0"
pyjwt = "2.10.1"
drf-recaptcha = "3.0.0"
twisted = "25.5.0"
daphne = "4.2.3"
typing-extensions = "4.15.0"
sentry-sdk = "2.35.0"
customerio = "1.4"
firebase-admin = "6.9.0"
openai = "^0.27.2"
websockets = "12.0"
stripe = "7.0.0"
msal = "^1.24.1"
pygments = "2.17.2"
markdown = "3.4.4"
django-guardian = "3.2.0"
drf-spectacular = "0.28.0"


[tool.poetry.group.dev.dependencies]
isort = "6.0.1"
pytest = "8.4.2"
pytest-django = "4.11.1"
mock = "5.2.0"
pytest-mock = "3.15.1"
pytest-asyncio = "0.26.0"
pre-commit = "4.3.0"
pytest-cov = "6.2.1"
ruff = "^0.14.0"
pycodestyle = "2.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
