# Generated by Django 2.2.13 on 2020-06-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200623_1650'),
        ('applications', '0009_auto_20200623_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='GenericWorkflow',
        ),
    ]
