# Generated by Django 2.2.7 on 2019-11-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20191107_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='application',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order (used in sorting from biggest to smaller)'),
        ),
    ]
