# Generated by Django 2.2.12 on 2020-06-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name of app'),
        ),
    ]
