# Generated by Django 2.2.13 on 2020-06-22 13:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20200612_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='workflow_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
