# Generated by Django 2.2.13 on 2020-06-23 14:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_is_workflow_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='workflow_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
