# Generated by Django 2.2 on 2025-12-05 12:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0137_auto_20251027_2214'),
        ('notifications', '0005_auto_20230526_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template name')),
                ('email_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('reset_password', 'Reset Password'), ('user_deactivated', 'User Deactivated'), ('new_task', 'New Task'), ('task_returned', 'Task Returned'), ('account_verification', 'Account Verification'), ('digest', 'Workflows Digest'), ('tasks_digest', 'Tasks Digest'), ('user_transfer', 'User Transfer'), ('unread_notifications', 'Unread Notifications'), ('guest_new_task', 'Guest New Task'), ('overdue_task', 'Overdue Task'), ('mention', 'Mention')], max_length=50), help_text='Email types that use this template', size=None, verbose_name='Email types')),
                ('subject', models.CharField(help_text='Use variables: {{variable_name}}', max_length=255, verbose_name='Subject')),
                ('content', models.TextField(help_text='HTML template with variables: {{variable_name}}', verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='accounts.Account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
                'ordering': ['account', 'name'],
            },
        ),
    ]
