# Generated by Django 2.2 on 2025-12-10 20:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_emailtemplatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatemodel',
            name='email_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('reset_password', 'Reset Password'), ('user_deactivated', 'User Deactivated'), ('new_task', 'New Task'), ('task_returned', 'Task Returned'), ('account_verification', 'Account Verification'), ('digest', 'Workflows Digest'), ('tasks_digest', 'Tasks Digest'), ('user_transfer', 'User Transfer'), ('unread_notifications', 'Unread Notifications'), ('guest_new_task', 'Guest New Task'), ('overdue_task', 'Overdue Task'), ('mention', 'Mention'), ('invite', 'Invite')], max_length=50), help_text='Email types that use this template', size=None, verbose_name='Email types'),
        ),
    ]
