# Generated by Django 2.2 on 2026-03-27 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20251211_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatemodel',
            name='email_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('reset_password', 'Reset Password'), ('user_deactivated', 'User Deactivated'), ('new_task', 'New Task'), ('task_returned', 'Task Returned'), ('task_reminder', 'Task Reminder'), ('account_verification', 'Account Verification'), ('digest', 'Workflows Digest'), ('tasks_digest', 'Tasks Digest'), ('user_transfer', 'User Transfer'), ('unread_notifications', 'Unread Notifications'), ('guest_new_task', 'Guest New Task'), ('overdue_task', 'Overdue Task'), ('mention', 'Mention'), ('invite', 'Invite'), ('complete_workflow', 'Complete Workflow'), ('vacation_delegation', 'Vacation Delegation')], max_length=50), help_text='Email types that use this template', size=None, verbose_name='Email types'),
        ),
    ]
