# Generated by Django 2.2.11 on 2020-04-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userinvite_invited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='active_templates',
            new_name='active_workflows',
        ),
    ]
