# Generated by Django 2.2.13 on 2020-06-16 09:32

from django.db import migrations
import pneumatic_backend.accounts.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20200609_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=pneumatic_backend.accounts.fields.EmailLowerField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='email',
            field=pneumatic_backend.accounts.fields.EmailLowerField(max_length=254),
        ),
    ]
