# Generated by Django 2.2.14 on 2020-07-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20200624_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClearBitUserInfo',
        ),
    ]
