# Generated by Django 2.2.14 on 2020-07-30 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from pneumatic_backend.generics.mixins.models import SoftDeleteMixin


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_delete_clearbituserinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=254)),
                ('avatar', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_self', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.Account')),
                ('users', models.ManyToManyField(related_name='group_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(SoftDeleteMixin, models.Model),
        ),
    ]
