# Generated by Django 2.2.16 on 2020-11-24 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_migrate_user_to_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invite',
        ),
    ]
