# Generated by Django 2.2.27 on 2022-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_auto_20220318_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarding_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE accounts_user SET is_onboarding_finished = TRUE
            WHERE account_id IN (
              SELECT id FROM accounts_account
              WHERE is_onboarding_finished
            ) AND is_deleted IS FALSE AND status = 'active'
            """,
        ),
    ]
