# Generated by Django 2.2 on 2024-03-15 16:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_auto_20240306_0731'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_username_unique',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
