# Generated by Django 2.2 on 2026-08-27 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models
import src.generics.mixins.services


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0147_auto_20260827_2155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0003_auto_20231123_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Display name of the provider', max_length=255)),
                ('base_url', models.URLField(max_length=1024)),
                ('api_key_encrypted', models.TextField()),
                ('vendor', models.CharField(choices=[('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('groq', 'Groq'), ('xai', 'xAI'), ('azure_openai', 'Azure OpenAI'), ('together', 'Together'), ('fireworks', 'Fireworks'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('cerebras', 'Cerebras'), ('perplexity', 'Perplexity'), ('huggingface', 'Hugging Face'), ('sambanova', 'SambaNova'), ('nvidia_nim', 'NVIDIA NIM'), ('openai_compatible', 'OpenAI compatible')], default='openai_compatible', help_text='Detected vendor of the provider API', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model, src.generics.mixins.services.EncryptionMixin),
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('model', models.CharField(help_text='OpenRouter-style model slug', max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('provider', models.ForeignKey(blank=True, help_text='NULL means the platform default connection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agents', to='ai.AIProvider')),
                ('user', models.ForeignKey(blank=True, help_text='The user the AI agent runs on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='aiagent',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('account', 'name'), name='aiagent_name_account_unique'),
        ),
    ]
