# Generated by Django 2.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20231123_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiprompt',
            name='model',
            field=models.CharField(
                choices=[
                    ('gpt-3.5-turbo', 'gpt-3.5-turbo'),
                    ('gpt-4-1106-preview', 'gpt-4-turbo-preview'),
                    ('gpt-4', 'gpt-4'),
                    ('gpt-4o', 'gpt-4o'),
                    ('gpt-4o-mini', 'gpt-4o-mini'),
                ],
                default='gpt-3.5-turbo',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name='openaiprompt',
            name='target',
            field=models.CharField(
                choices=[
                    ('get_steps', 'Get template steps'),
                    ('get_template', 'Get full template (JSON)'),
                ],
                default='get_steps',
                max_length=200,
            ),
        ),
    ]
