# Generated by Django 2.2.28 on 2026-09-19 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models
import src.generics.mixins.services


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0260_auto_20260914_1039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0146_user_is_ai'),
        ('ai', '0003_auto_20231123_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_prompt', models.TextField()),
                ('model', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Display name of the provider', max_length=255)),
                ('base_url', models.URLField(max_length=1024)),
                ('api_key_encrypted', models.TextField()),
                ('vendor', models.CharField(choices=[('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('groq', 'Groq'), ('deepseek', 'DeepSeek')], help_text='Detected type of the provider API', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model, src.generics.mixins.services.EncryptionMixin),
        ),
        migrations.CreateModel(
            name='AIAgentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('task_in_progress', 'Task in progress'), ('reading_description', 'Reading task description'), ('request', 'Request'), ('error', 'Error'), ('mention_in_progress', 'Mention in progress')], max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ai.AIAgent')),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agent_action', to='accounts.Notification')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_agent_actions', to='processes.Task')),
            ],
            options={
                'ordering': ('-date_created', 'id'),
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='provider',
            field=models.ForeignKey(help_text='NULL means the platform default connection', on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to='ai.AIProvider'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='user',
            field=models.OneToOneField(help_text='The user the AI agent runs on', on_delete=django.db.models.deletion.CASCADE, related_name='ai_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiagentaction',
            index=models.Index(fields=['agent', 'task', 'action', 'date_created'], name='aiagentaction_claim_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiagent',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('account', 'name'), name='aiagent_name_account_unique'),
        ),
    ]
