# Generated by Django 2.2 on 2026-07-22 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0255_add_fieldsets'),
        ('accounts', '0144_auto_20260609_1910'),
        ('ai', '0003_auto_20231123_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(default='https://openrouter.ai/api/v1', max_length=1024)),
                ('api_key', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_connections', to='accounts.Account')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('model_slug', models.CharField(help_text='OpenRouter-style model slug, e.g. anthropic/claude-3', max_length=200)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('temperature', models.FloatField(blank=True, help_text='NULL means the provider default', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('max_tokens', models.IntegerField(blank=True, help_text='NULL means the provider default', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('photo', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to='accounts.Account')),
                ('connection', models.ForeignKey(blank=True, help_text='NULL means the platform default connection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agents', to='ai.AIProviderConnection')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AITaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('completed', 'completed'), ('left_for_human', 'left_for_human'), ('failed', 'failed')], default='queued', max_length=32)),
                ('reason', models.TextField(blank=True, help_text='Why the task was left for a human or failed', null=True)),
                ('model_used', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='ai.AIAgent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_task_runs', to='processes.Task')),
            ],
            options={
                'ordering': ('-date_created',),
                'unique_together': {('task', 'agent')},
            },
        ),
        migrations.AddConstraint(
            model_name='aiagent',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('account', 'name'), name='aiagent_name_account_unique'),
        ),
    ]
