# Generated by Django 2.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_add_model_choices_and_template_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiprompt',
            name='model',
            field=models.CharField(
                choices=[
                    ('gpt-4.1-mini', 'gpt-4.1-mini (recommended)'),
                    ('gpt-4.1', 'gpt-4.1'),
                    ('gpt-4.1-nano', 'gpt-4.1-nano'),
                    ('gpt-5', 'gpt-5'),
                    ('gpt-5-mini', 'gpt-5-mini'),
                    ('o3', 'o3'),
                    ('o4-mini', 'o4-mini'),
                    ('gpt-4o', 'gpt-4o'),
                    ('gpt-4o-mini', 'gpt-4o-mini'),
                    ('gpt-4', 'gpt-4'),
                    ('gpt-3.5-turbo', 'gpt-3.5-turbo'),
                    ('gpt-4-1106-preview', 'gpt-4-turbo-preview'),
                ],
                default='gpt-3.5-turbo',
                max_length=200,
            ),
        ),
    ]
