# Generated by Django 2.2.5 on 2019-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleauth',
            name='photo',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
