# Generated by Django 2.2.28 on 2022-05-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_auto_20220602_0552'),
        ('processes', '0171_auto_20221031_1342'),
        ('notifications', '0002_auto_20220524_1339'),
    ]

    operations = [
    ]
