# Generated by Django 2.2.10 on 2020-02-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_auto_20200124_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, 'Process in work'), (1, 'Process done'), (2, 'Process aborted')], default=0),
        ),
    ]
