# Generated by Django 2.2.12 on 2020-04-25 00:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0023_task_responsible'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskComplete',
            new_name='TaskResponsible',
        ),
    ]
