# Generated by Django 2.2.12 on 2020-04-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0024_auto_20200425_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete_by_all',
            new_name='require_completion_by_all',
        ),
        migrations.RenameField(
            model_name='taskworkflow',
            old_name='complete_by_all',
            new_name='require_completion_by_all',
        ),
    ]