# Generated by Django 2.2.12 on 2020-05-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0028_auto_20200508_2003'),
        ('processes', '0027_merge_20200508_1047'),
    ]

    operations = [
    ]
