# Generated by Django 2.2.13 on 2020-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0033_auto_20200623_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='taskworkflow',
            name='name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
