# Generated by Django 2.2.13 on 2020-06-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0036_auto_20200629_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtemplate',
            name='kickoff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.Kickoff'),
        ),
    ]
