# Generated by Django 2.2.14 on 2020-07-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0044_auto_20200710_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldselection',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name='fieldselection',
            options={'ordering': ['pk']},
        ),
    ]
