# Generated by Django 2.2.16 on 2020-10-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0076_auto_20200930_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='processes.Process'),
        ),
    ]
