# Generated by Django 2.2.16 on 2020-11-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0092_auto_20201109_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='type',
            field=models.CharField(choices=[('custom', 'custom'), ('generic', 'generic'), ('generic_clone', 'generic clone'), ('invited_onboarding_admin', 'Invited admin users onboarding workflow'), ('invited_onboarding_regular', 'Invited regular users onboarding workflow'), ('onboarding_owner', 'Owner onboarding')], default='custom', max_length=48),
        ),
    ]
