# Generated by Django 2.2.17 on 2021-03-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0105_templateversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldselection',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='processes.FieldTemplateSelection'),
        ),
        migrations.AddField(
            model_name='kickoffvalue',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='processes.Kickoff'),
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='processes.TaskWorkflow'),
        ),
        migrations.AddField(
            model_name='taskfield',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='processes.FieldTemplate'),
        ),
    ]
