# Generated by Django 2.2.17 on 2021-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0108_merge_20210315_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldselection',
            name='api_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fieldtemplateselection',
            name='api_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
