# Generated by Django 2.2.17 on 2021-04-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0122_auto_20210426_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtemplateselection',
            options={'ordering': ['pk']},
        ),
    ]
