# Generated by Django 2.2.24 on 2021-06-22 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0139_auto_20210622_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow', to=settings.AUTH_USER_MODEL),
        ),
        # Bad trigger - it don't update search_content when field updated
        migrations.RunSQL(
            sql='''
                CREATE OR REPLACE FUNCTION tsvector_update_trigger_on_workflow()
                  RETURNS trigger AS
                $BODY$
                BEGIN
                SELECT to_tsvector(CONCAT(new.name) || ' ' || CONCAT(string_agg(wf.name, ' ')) || ' ' || CONCAT(string_agg(pt.value, ' ')) || ' ' || CONCAT(string_agg(wf2.value, ' ')))
                INTO new.search_content
                FROM processes_workflow pw
                       LEFT JOIN processes_kickoffvalue kv ON kv.workflow_id = pw.id AND pw.is_deleted is FALSE
                       LEFT JOIN processes_fileattachment wf ON wf.workflow_id = pw.id AND wf.is_deleted is FALSE
                       LEFT JOIN processes_taskfield pt on kv.id = pt.kickoff_id AND pt.is_deleted is FALSE
                       LEFT JOIN processes_fieldselection wf2
                         on pt.id = wf2.field_id AND wf2.is_selected is TRUE AND wf2.is_deleted is FALSE
                WHERE pw.id= new.id;
                  RETURN new;
                END;
                $BODY$
                  LANGUAGE plpgsql;
                ''',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='''
                CREATE TRIGGER process_ins BEFORE INSERT OR UPDATE ON processes_workflow FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger_on_workflow();
                ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS process_ins ON processes_workflow;
                '''
        ),
        migrations.RunSQL(
            sql='''
                CREATE OR REPLACE FUNCTION tsvector_update_trigger_on_fileattachment()
                  RETURNS trigger AS
                $BODY$
                BEGIN
                  UPDATE processes_workflow
                  SET name=name
                  WHERE processes_workflow.id = new.workflow_id;
                  RETURN new;
                end;
                $BODY$
                  LANGUAGE plpgsql;
                ''',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='''
                CREATE TRIGGER fileattachments_ins AFTER INSERT OR UPDATE ON processes_fileattachment FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger_on_fileattachment();
                ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS fileattachments_ins ON processes_fileattachment;
                '''
        ),
        migrations.RunSQL(
            sql='''
                CREATE OR REPLACE FUNCTION tsvector_update_trigger_on_taskfield()
                  RETURNS TRIGGER AS
                $BODY$
                BEGIN
                  UPDATE processes_task SET name = name WHERE id = new.task_id;
                  UPDATE processes_workflow w
                  SET name = name
                         FROM processes_kickoffvalue k
                  WHERE k.id = new.kickoff_id AND k.workflow_id=w.id;
                  RETURN new;
                END;
                $BODY$
                LANGUAGE plpgsql;
                ''',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='''
                CREATE TRIGGER taskfield_ins AFTER INSERT OR UPDATE ON processes_taskfield FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger_on_taskfield();
                ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS taskfield_ins ON processes_taskfield;
                '''
        ),
    ]
