# Generated by Django 2.2.24 on 2021-09-02 13:39

from django.db import migrations

create_kickoff_for_inactive_template_sql = """
    WITH orphan_template AS (
        SELECT
          FALSE AS is_deleted, 
          '' AS description,
          pt.account_id,
          pt.id AS template_id 
        FROM processes_template pt 
          LEFT JOIN processes_kickoff pk ON pt.id = pk.template_id
        WHERE pt.is_deleted IS FALSE AND pk.id IS NULL
    )
    INSERT INTO processes_kickoff (
      is_deleted, 
      description, 
      account_id, 
      template_id
    )
    SELECT is_deleted, description, account_id, template_id
    FROM orphan_template
"""

create_kickoff_id_for_drafts_sql = """
    WITH broken_draft AS (
    SELECT 
      ptd.id,
      jsonb_build_object(
        'kickoff',
         ptd.draft->'kickoff' || jsonb_build_object('id', pk.id)
      ) AS kickoff_draft
    FROM processes_template pt
      JOIN processes_kickoff pk ON pt.id=pk.template_id
      JOIN processes_templatedraft ptd ON ptd.template_id=pt.id   
    WHERE 
        pt.is_deleted IS FALSE 
        AND pk.is_deleted is FALSE
        AND ptd.is_deleted IS FALSE
        AND draft->'kickoff'->'id' IS NULL
        AND pt.is_active IS FALSE
        AND ptd.id IS NOT NULL
    )
    UPDATE processes_templatedraft main SET draft = draft || broken_draft.kickoff_draft
    FROM broken_draft
    WHERE broken_draft.id = main.id
"""


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0144_create_still_kickoff_value'),
    ]

    operations = [
        migrations.RunSQL(
            sql=create_kickoff_for_inactive_template_sql,
            reverse_sql=""""""
        ),
        migrations.RunSQL(
            sql=create_kickoff_id_for_drafts_sql,
            reverse_sql=""""""
        )
    ]
