# Generated by Django 2.2.27 on 2022-04-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0155_auto_20220419_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-date_created']},
        ),
    ]
