# Generated by Django 2.2.28 on 2022-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0170_checklistselection_value_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistselection',
            name='date_selected',
            field=models.DateTimeField(null=True, verbose_name='The date the selection was marked'),
        ),
        migrations.AlterField(
            model_name='checklistselection',
            name='selected_user_id',
            field=models.IntegerField(null=True, verbose_name='The user who mark or unmark selection'),
        ),
        migrations.AlterField(
            model_name='checklistselection',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklistselection',
            name='value_template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklisttemplateselection',
            name='value',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='name_template',
            field=models.TextField(),
        ),
    ]
