# Generated by Django 2.2.28 on 2023-03-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0184_migrate_due_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date_directly_status',
            field=models.IntegerField(choices=[(0, 'no status'), (1, 'deleted'), (2, 'created')], default=0),
        ),
    ]
