# Generated by Django 2.2 on 2023-04-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0186_auto_20230331_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_in',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='due_in',
        ),
    ]
