# Generated by Django 2.2 on 2023-12-28 07:32

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0196_task_contains_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='search_content',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
