# Generated by Django 2.2 on 2024-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0202_remove_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='wf_name_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='wf_name_template_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='name_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='generic_name',
            field=models.CharField(blank=True, help_text='Used in system templates. Possible dynamic values: account_name, user_first_name, user_last_name, user_email', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='legacy_template_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.TextField(),
        ),
    ]
