# Generated by Django 2.2 on 2024-08-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0210_migrate_system_templates'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE processes_systemtemplate
              SET template = template || jsonb_build_object('wf_name_template', '{{date}} — {{template-name}}')
            WHERE is_deleted IS FALSE
        """),
        migrations.RunSQL("""
            UPDATE processes_template
              SET wf_name_template = '{{date}} — {{template-name}}'
            WHERE is_deleted IS FALSE
              AND wf_name_template IS NULL
              AND type NOT IN (
                'builtin_admin_onboarding',
                'builtin_user_onboarding',
                'builtin_account_owner_onboarding'
              )
        """)
    ]
