# Generated by Django 2.2 on 2024-09-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0211_migrate_system_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawperformer',
            name='api_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawperformertemplate',
            name='api_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.RunSQL("""
            UPDATE processes_rawperformertemplate
            SET api_name = 'raw-performer-' || upper(substr(md5(random()::text), 0, 10))
        """),
            migrations.RunSQL("""
            UPDATE processes_rawperformer AS rp
            SET api_name = rpt.api_name
            FROM processes_rawperformertemplate AS rpt
            WHERE rp.template_id = rpt.id
        """)
    ]
