# Generated by Django 2.2 on 2024-11-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0219_auto_20241126_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='fieldselection',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='kickoffvalue',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='predicate',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='rawperformer',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='taskfield',
            name='template_id',
        ),
    ]
