# Generated by Django 2.2 on 2025-02-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0223_migrate_template_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='revert_task',
            field=models.CharField(blank=True, help_text='Api name task to revert', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='revert_task',
            field=models.CharField(blank=True, help_text='Api name task to revert', max_length=255, null=True),
        ),
        migrations.RunSQL(
            """
            -- For every template draft task set default "revert_task" value as null
            WITH new AS (
                SELECT 
                  ptd.id,
                  ptd.draft || jsonb_build_object(                                   -- Rewrite draft tasks with updated tasks
                    'tasks',
                    (
                       SELECT jsonb_agg(                                             -- Construct updated tasks JSON array  
                         CASE
                           WHEN NOT elem ? 'revert_task'                             -- If 'revert_task' key not exists in task
                             THEN elem || jsonb_build_object('revert_task', NULL)    -- Set new task property 'revert_task': null
                           ELSE elem                                                 -- Else add to array unchanged task
                         END
                       )
                       FROM jsonb_array_elements(draft->'tasks') AS elem             -- Iterate tasks
                    )
                  ) AS draft
                FROM processes_templatedraft ptd
                INNER JOIN processes_template pt ON pt.id = ptd.template_id
                WHERE pt.is_deleted IS FALSE
                  AND ptd.is_deleted IS FALSE
                  AND jsonb_typeof(draft->'tasks') = 'array'
            )
            UPDATE processes_templatedraft
            SET draft = processes_templatedraft.draft || new.draft
            FROM new
            WHERE new.id = processes_templatedraft.id
            """
        ),
        migrations.RunSQL(
            """
            WITH new AS (
            SELECT 
              id,
              template || jsonb_build_object(
                'tasks',
                (
                   SELECT jsonb_agg(
                     CASE
                       WHEN NOT elem ? 'revert_task'
                         THEN elem || jsonb_build_object('revert_task', NULL)
                       ELSE elem
                     END
                   )
                   FROM jsonb_array_elements(template->'tasks') AS elem
                )
              ) AS template
            FROM processes_systemtemplate 
            WHERE is_deleted IS FALSE
              AND jsonb_typeof(template->'tasks') = 'array'
            )
            UPDATE processes_systemtemplate
            SET template = processes_systemtemplate.template || new.template
            FROM new
            WHERE new.id = processes_systemtemplate.id
            """
        )
    ]

