# Generated by Django 2.2 on 2025-02-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0225_auto_20250128_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='template_owners',
        ),
    ]
