# Generated by Django 2.2 on 2025-05-14 13:04
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0229_auto_20250404_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='active_current_task',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='active_tasks_count',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='tasks_count',
        ),
    ]
