# Generated by Django 2.2 on 2025-06-02 21:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0230_auto_20250514_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parents',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list,
                help_text='Api names of task parents. Only those ancestors that caused the task to start.', size=None),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='parents',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list,
                help_text='Api names of task parents', size=None),
        ),
    ]
