# Generated by Django 2.2 on 2025-07-03 21:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0231_auto_20250602_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='ancestors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text='Api names of task ancestors', size=None),
        )
    ]
