# Generated by Django 2.2 on 2025-07-15 11:36
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0232_auto_20250703_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='current_task',
        ),
    ]
