# Generated by Django 2.2 on 2025-08-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0233_remove_current_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Workflow'),
        ),
        migrations.RunSQL("""
            UPDATE processes_delay
            SET workflow_id = result.workflow_id
            FROM (
                SELECT 
                  pd.id AS id,
                  pt.workflow_id AS workflow_id
                FROM processes_delay pd
                  INNER JOIN processes_task pt
                    ON pt.id = pd.task_id
            ) result
            WHERE processes_delay.id = result.id
        """),

    ]
