# Generated by Django 2.2 on 2024-10-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0234_auto_20250804_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kickoff',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kickoffvalue',
            name='description',
        ),
    ]
