# Generated by Django 2.2 on 2025-09-10 16:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0235_auto_20241016_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('account', 'Account')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_presets', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='processes.Template')),
            ],
            options={
                'ordering': ['-date_created'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TemplatePresetField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=100)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.TemplatePreset')),
            ],
            options={
                'ordering': ['api_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='templatepresetfield',
            constraint=models.UniqueConstraint(fields=('preset', 'api_name'), name='processes_templatepresetfield_preset_api_name_unique'),
        ),
    ]
