# Generated by Django 2.2 on 2025-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0236_auto_20250910_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepreset',
            name='name',
            field=models.CharField(default='Default Name', max_length=200),
            preserve_default=False,
        ),
    ]
