# Generated by Django 2.2 on 2025-07-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0131_add_bucket_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0238_update_user_field_values_in_workflow_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicate',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserGroup'),
        ),
        migrations.AddField(
            model_name='predicate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predicatetemplate',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserGroup'),
        ),
        migrations.AddField(
            model_name='predicatetemplate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='field_type',
            field=models.CharField(choices=[('kickoff', 'kickoff'), ('task', 'task'), ('string', 'string'), ('text', 'text'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('date', 'date'), ('url', 'url'), ('dropdown', 'dropdown'), ('file', 'file'), ('user', 'user'), ('group', 'group'), ('number', 'number')], max_length=20),
        ),
        migrations.AlterField(
            model_name='predicatetemplate',
            name='field_type',
            field=models.CharField(choices=[('kickoff', 'kickoff'), ('task', 'task'), ('string', 'string'), ('text', 'text'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('date', 'date'), ('url', 'url'), ('dropdown', 'dropdown'), ('file', 'file'), ('user', 'user'), ('group', 'group'), ('number', 'number')], max_length=20),
        ),
    ]
