# Generated by Django 2.2 on 2025-10-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0240_populate_user_group_predicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='access_type',
            field=models.CharField(choices=[('account', 'account'), ('restricted', 'restricted')], default='account', max_length=20),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='file_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
