# Generated by Django 2.2 on 2026-01-20 13:23

import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0241_remove_old_search_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowEvent')),
                ('sys_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.SystemTemplate')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Task')),
                ('task_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.TaskField')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Workflow')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='searchcontent',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('workflow', 'task', 'sys_template', 'event', 'task_field'), name='processes_search_content_unique'),
        ),
    ]
