# Generated by Django 2.2 on 2026-01-20 13:23

import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0241_remove_old_search_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtemplate',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='accounts.Account'),
        ),

        migrations.AlterField(
            model_name='taskfield',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='accounts.Account'),
        ),
        migrations.CreateModel(
            name='SearchContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowEvent')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Task')),
                ('task_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.TaskField')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Workflow')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Template')),
                ('task_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.TaskTemplate')),
                ('content', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('type', models.CharField(
                    max_length=50,
                    choices=(
                        ('workflow', 'workflow'),
                        ('kickoff_field', 'kickoff_field'),
                        ('task_field', 'task_field'),
                        ('task', 'task'),
                        ('template', 'template'),
                        ('event', 'event'),
                        ('template_task', 'template_task'),
                    )
                )),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='searchcontent',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('workflow', 'task', 'event', 'task_field', 'template', 'task_template'), name='processes_search_content_unique'),
        ),
        # create prepare search text func
        migrations.RunSQL("""
         -- Union text parts and excluding unwanted lexemes (www, <, >, **) from the text
             CREATE OR REPLACE FUNCTION prepare_search_content(TEXT default '', TEXT default '', TEXT default '', TEXT default '')
             RETURNS TEXT AS $$ 
             BEGIN
               RETURN REGEXP_REPLACE(CONCAT($1, ' ', $2, ' ', $3, ' ', $4), 'http(s)?:\\\\(www\.)?|www\.|\<|\>|\*\*', '', 'g');
             END;
             $$ LANGUAGE plpgsql;
        """),
        # processes_workflow search content (workflow name has weight "A", template name has weight "C" )
        migrations.RunSQL(sql="""
            CREATE OR REPLACE FUNCTION create_workflow_search_content()
            RETURNS trigger AS 
            $BODY$
                BEGIN
                INSERT INTO processes_searchcontent (
                    type, is_deleted, account_id, event_id, task_id, task_field_id, workflow_id, template_id, task_template_id, content
                )
                VALUES (
                    'workflow', FALSE, new.account_id, NULL, NULL, NULL, new.id, NULL, NULL, 
                    (
                        setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.name)), 'A') ||
                        setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.legacy_template_name)), 'C')
                    )
                )
                ON CONFLICT (workflow_id, task_id, event_id, task_field_id, template_id, task_template_id) WHERE is_deleted = FALSE
                DO UPDATE SET content = (
                    setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.name)), 'A') ||
                    setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.legacy_template_name)), 'C')
                );
                RETURN new;
            END;
            $BODY$ LANGUAGE plpgsql;
        """),
        migrations.RunSQL(sql="""
            CREATE TRIGGER workflow_insert AFTER INSERT OR UPDATE ON processes_workflow 
            FOR EACH ROW EXECUTE FUNCTION create_workflow_search_content()
        """),

        # processes_task search content (task name has weight "D", task description has weight "B")
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION create_task_search_content()
            RETURNS trigger AS 
            $BODY$
                BEGIN
                INSERT INTO processes_searchcontent (
                    type, is_deleted, account_id, event_id, task_id, task_field_id, workflow_id, template_id, task_template_id, content
                )
                VALUES (
                    'task', FALSE, new.account_id, NULL, new.id, NULL, new.workflow_id, NULL, NULL, (
                        setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.description)), 'B') ||
                        setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.name)), 'D')
                    )
                )
                ON CONFLICT (workflow_id, task_id, event_id, task_field_id, template_id, task_template_id) WHERE is_deleted = FALSE
                DO UPDATE SET content = (
                    setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.description)), 'B') ||
                    setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.name)), 'D')
                );
                RETURN new;
            END;
            $BODY$ LANGUAGE plpgsql;
        """),
            migrations.RunSQL(sql="""
             CREATE TRIGGER task_insert AFTER INSERT OR UPDATE ON processes_task 
             FOR EACH ROW EXECUTE FUNCTION create_task_search_content()
        """),

        # processes_taskfield search content (kickoff field value has weight "B", task field value has weight "C" )
        migrations.RunSQL(sql="""
            CREATE OR REPLACE FUNCTION create_taskfield_search_content()
            RETURNS trigger AS 
            $BODY$
                BEGIN
                INSERT INTO processes_searchcontent (
                    type, is_deleted, account_id, event_id, task_id, task_field_id, workflow_id, template_id, task_template_id, content
                )
                VALUES (                
                    CASE
                        WHEN new.kickoff_id IS NOT NULL THEN 'kickoff_field'
                        ELSE 'task_field'
                    END,
                    FALSE, new.account_id, NULL, new.task_id, new.id, new.workflow_id, NULL, NULL,
                    CASE
                        WHEN new.kickoff_id IS NOT NULL THEN setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.value)), 'B')
                        ELSE setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.value)), 'C')
                    END
                )
                ON CONFLICT (workflow_id, task_id, event_id, task_field_id, template_id, task_template_id) WHERE is_deleted = FALSE
                DO UPDATE SET content = CASE
                    WHEN new.kickoff_id IS NOT NULL THEN setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.value)), 'B')
                    ELSE setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.value)), 'C')
                END;
                RETURN new;
            END;
            $BODY$ LANGUAGE plpgsql;
        """),
        migrations.RunSQL(sql="""
             CREATE TRIGGER workflow_ins AFTER INSERT OR UPDATE ON processes_taskfield
             FOR EACH ROW EXECUTE FUNCTION create_taskfield_search_content()
        """),

        # processes_workflowevent search content (event with type "comment" text has weight "D" )
        migrations.RunSQL(sql="""
            CREATE OR REPLACE FUNCTION create_workflowevent_search_content()
            RETURNS trigger AS
            $BODY$
                BEGIN
                INSERT INTO processes_searchcontent (
                    type, is_deleted, account_id, event_id, task_id, task_field_id, workflow_id, template_id, task_template_id, content
                )
                VALUES (
                    'event', FALSE, new.account_id, new.id, new.task_id, NULL, new.workflow_id, NULL, NULL, setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.text)), 'D')
                )
                ON CONFLICT (workflow_id, task_id, event_id, task_field_id, template_id, task_template_id) WHERE is_deleted = FALSE
                DO UPDATE SET content =  setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.text)), 'D');
                RETURN new;
            END;
            $BODY$ LANGUAGE plpgsql;
        """),
        migrations.RunSQL(sql="""
            CREATE TRIGGER workflowevent_insert AFTER INSERT OR UPDATE ON processes_workflowevent 
            FOR EACH ROW 
            WHEN (new.type = 5)
            EXECUTE FUNCTION create_workflowevent_search_content()
        """),

        # processes_template search content (name has weight "C", description has weight "D")
        migrations.RunSQL(sql="""
            CREATE OR REPLACE FUNCTION create_template_search_content()
            RETURNS trigger AS
            $BODY$
                BEGIN
                INSERT INTO processes_searchcontent (
                    type, is_deleted, account_id, event_id, task_id, task_field_id, workflow_id, template_id, task_template_id, content
                )
                VALUES (
                        'template', FALSE, new.account_id, NULL, NULL, NULL, NULL, new.id, NULL, (
                        setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.name)), 'C') ||
                        setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.description)), 'D')   
                    )
                )
                ON CONFLICT (workflow_id, task_id, event_id, task_field_id, template_id, task_template_id) WHERE is_deleted = FALSE
                DO UPDATE SET content = (
                    setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.name)), 'C') ||
                    setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.description)), 'D')   
                );
                RETURN new;
            END;
            $BODY$ LANGUAGE plpgsql;
        """),
        migrations.RunSQL(sql="""
             CREATE TRIGGER template_ins AFTER INSERT OR UPDATE ON processes_template
             FOR EACH ROW EXECUTE FUNCTION create_template_search_content()
        """),

        # processes_task_template search content (name has weight "D")
        migrations.RunSQL(sql="""
            CREATE OR REPLACE FUNCTION create_task_template_search_content()
            RETURNS trigger AS
            $BODY$
                BEGIN
                INSERT INTO processes_searchcontent (
                    type, is_deleted, account_id, event_id, task_id, task_field_id, workflow_id, template_id, task_template_id, content
                )
                VALUES (
                    'task_template', FALSE, new.account_id, NULL, NULL, NULL, NULL, new.template_id, new.id,
                    (
                      setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.name)), 'D') ||
                      setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.description)), 'D')
                    )
                )
                ON CONFLICT (workflow_id, task_id, event_id, task_field_id, template_id, task_template_id) WHERE is_deleted = FALSE
                DO UPDATE SET content = setweight(to_tsvector('pg_catalog.english', prepare_search_content(new.name)), 'D');
                RETURN new;
            END;
            $BODY$ LANGUAGE plpgsql;
        """),
        migrations.RunSQL(sql="""
             CREATE TRIGGER task_template_ins AFTER INSERT OR UPDATE ON processes_tasktemplate
             FOR EACH ROW EXECUTE FUNCTION create_task_template_search_content()
        """),
        migrations.RunSQL(sql="UPDATE processes_workflow SET name=name"),
        migrations.RunSQL(sql="UPDATE processes_task SET name=name"""),
        migrations.RunSQL(sql="UPDATE processes_taskfield SET type=type"),
        migrations.RunSQL(sql="UPDATE processes_workflowevent SET type=type"),
        migrations.RunSQL(sql="UPDATE processes_template SET name=name"),
        migrations.RunSQL(sql="UPDATE processes_tasktemplate SET name=name"),
    ]
