# Generated by Django 2.2 on 2026-02-12 15:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0242_add_new_search_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='completion_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='reminder_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='completion_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='reminder_notification',
            field=models.BooleanField(default=False),
        ),
    ]
