# Generated by Django 2.2 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0244_add_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateowner',
            name='role',
            field=models.CharField(
                choices=[
                    ('owner', 'owner'),
                    ('viewer', 'viewer'),
                    ('starter', 'starter'),
                ],
                default='owner',
                max_length=100,
            ),
        ),
        migrations.AlterModelOptions(
            name='templateowner',
            options={'ordering': ['role', 'type', 'id']},
        ),
        migrations.AddConstraint(
            model_name='templateowner',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_deleted=False, type='user'),
                fields=['template', 'user', 'role'],
                name='processes_template_owner_user_role_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='templateowner',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_deleted=False, type='group'),
                fields=['template', 'group', 'role'],
                name='processes_template_owner_group_role_unique',
            ),
        ),
    ]
