# Generated by Django 2.2 on 2026-03-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0245_add_templateowner_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfield',
            name='clear_value',
            field=models.TextField(default='', help_text='Does not contains markdown'),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='markdown_value',
            field=models.TextField(default='', help_text='Contains markdown representation'),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='value',
            field=models.TextField(default='', help_text='Human readable value'),
        ),
    ]
