# Generated by Django 2.2 on 2026-03-17 15:15

from django.db import migrations, models


def set_taskfield_empty_values(apps, schema_editor):
    TaskField = apps.get_model('processes', 'TaskField')
    TaskField.objects.filter(clear_value__isnull=True).update(clear_value='')
    TaskField.objects.filter(markdown_value__isnull=True).update(
        markdown_value='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0245_add_templateowner_role'),
    ]

    operations = [
        migrations.RunPython(
            set_taskfield_empty_values,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='clear_value',
            field=models.TextField(default='', help_text='Does not contains markdown'),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='markdown_value',
            field=models.TextField(default='', help_text='Contains markdown representation'),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='value',
            field=models.TextField(default='', help_text='Human readable value'),
        ),
    ]
