# Generated by Django 2.2 on 2026-04-03 12:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0248_migrate_selections'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fieldtemplateselection',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('field_template', 'value'), name='processes_fieldtemplateselection_field_template_value_unique'),
        ),
    ]
