# Generated by Django 2.2 on 2026-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0250_workflowevent_type_add_task_delegated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='skip_for_starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='skip_for_starter',
            field=models.BooleanField(default=False),
        ),
    ]
