# Generated by Django 2.2 on 2026-04-28 09:42

from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0142_vacation_fields'),
        ('processes', '0251_add_skip_for_starter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('label_position', models.CharField(choices=[('top', 'Top'), ('left', 'Left')], default='top', max_length=20)),
                ('name', models.TextField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('layout', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='vertical', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('kickoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='processes.KickoffValue')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='processes.Task')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='processes.Workflow')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldSetRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('sum_equal', 'The sum is equal')], max_length=50)),
                ('value', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='processes.FieldSet')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldsetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('label_position', models.CharField(choices=[('top', 'Top'), ('left', 'Left')], default='top', max_length=20)),
                ('name', models.TextField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('layout', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='vertical', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='processes.Template')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldsetTemplateRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('sum_equal', 'The sum is equal')], max_length=50)),
                ('value', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='processes.FieldsetTemplate')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldsetTemplateTaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.FieldsetTemplate')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.TaskTemplate')),
            ],
            options={
                'db_table': 'processes_fieldsettemplate_tasktemplate',
                'ordering': ['order'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldsetTemplateKickoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.FieldsetTemplate')),
                ('kickoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Kickoff')),
            ],
            options={
                'db_table': 'processes_fieldsettemplate_kickoff',
                'ordering': ['order'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='fieldsettemplate',
            name='kickoffs',
            field=models.ManyToManyField(blank=True, related_name='fieldsets', through='processes.FieldsetTemplateKickoff', to='processes.Kickoff'),
        ),
        migrations.AddConstraint(
            model_name='fieldsettemplate',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_deleted=False),
                fields=('template', 'api_name'),
                name='fieldsettemplate_api_name_template_unique'),
        ),
        migrations.AddField(
            model_name='fieldsettemplate',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='fieldsets', through='processes.FieldsetTemplateTaskTemplate', to='processes.TaskTemplate'),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.Template'),
        ),
        migrations.AddField(
            model_name='fieldtemplate',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.FieldsetTemplate'),
        ),
        migrations.AddField(
            model_name='fieldtemplate',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='fields', to='processes.FieldsetTemplateRule'),
        ),
        migrations.AddField(
            model_name='taskfield',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.FieldSet'),
        ),
        migrations.AddField(
            model_name='taskfield',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='fields', to='processes.FieldSetRule'),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='operator',
            field=models.CharField(
                choices=[('equals', 'Equal'), ('not_equals', 'Not equal'),
                         ('exists', 'Exists'), ('not_exists', 'Not exists'),
                         ('contains', 'Contains'),
                         ('not_contains', 'Not contains'),
                         ('more_than', 'More than'),
                         ('less_than', 'Less than'),
                         ('completed', 'completed'), ('skipped', 'skipped'),
                         ('completed_or_skipped', 'completed_or_skipped')],
                max_length=30),
        ),
        migrations.AlterField(
            model_name='predicatetemplate',
            name='operator',
            field=models.CharField(
                choices=[('equals', 'Equal'), ('not_equals', 'Not equal'),
                         ('exists', 'Exists'), ('not_exists', 'Not exists'),
                         ('contains', 'Contains'),
                         ('not_contains', 'Not contains'),
                         ('more_than', 'More than'),
                         ('less_than', 'Less than'),
                         ('completed', 'completed'), ('skipped', 'skipped'),
                         ('completed_or_skipped', 'completed_or_skipped')],
                max_length=30),
        ),
        migrations.RunSQL("""
            UPDATE processes_predicate p
            SET    operator = 'completed_or_skipped'
            FROM   processes_rule r
            WHERE  p.rule_id    = r.id
              AND  p.operator   = 'completed'
              AND  p.field_type = 'task'
        """),
            migrations.RunSQL("""
            UPDATE processes_predicatetemplate pt
            SET    operator = 'completed_or_skipped'
            FROM   processes_ruletemplate rt
            WHERE  pt.rule_id   = rt.id
              AND  pt.operator  = 'completed'
              AND  pt.field_type = 'task'
        """),
        migrations.RunSQL("""
            UPDATE processes_templatedraft td
            SET draft = (
                SELECT jsonb_set(
                    td.draft,
                    '{tasks}',
                    jsonb_agg(
                        CASE
                            WHEN jsonb_typeof(task->'conditions') = 'array' THEN
                                jsonb_set(
                                    task,
                                    '{conditions}',
                                    (
                                        SELECT jsonb_agg(
                                            CASE
                                                WHEN jsonb_typeof(cond->'rules') = 'array' THEN
                                                    jsonb_set(
                                                        cond,
                                                        '{rules}',
                                                        (
                                                            SELECT jsonb_agg(
                                                                CASE
                                                                    WHEN jsonb_typeof(rule->'predicates') = 'array' THEN
                                                                        jsonb_set(
                                                                            rule,
                                                                            '{predicates}',
                                                                            (
                                                                                SELECT jsonb_agg(
                                                                                    CASE
                                                                                        WHEN (pred->>'operator') = 'completed'
                                                                                         AND (pred->>'field_type') = 'task'
                                                                                        THEN jsonb_set(pred, '{operator}', '"completed_or_skipped"')
                                                                                        ELSE pred
                                                                                    END
                                                                                )
                                                                                FROM jsonb_array_elements(rule->'predicates') AS pred
                                                                            )
                                                                        )
                                                                    ELSE rule
                                                                END
                                                            )
                                                            FROM jsonb_array_elements(cond->'rules') AS rule
                                                        )
                                                    )
                                                ELSE cond
                                            END
                                        )
                                        FROM jsonb_array_elements(task->'conditions') AS cond
                                    )
                                )
                            ELSE task
                        END
                    )
                )
                FROM jsonb_array_elements(td.draft->'tasks') AS task
            )
            WHERE td.is_deleted = FALSE
              AND td.draft IS NOT NULL
              AND jsonb_typeof(td.draft->'tasks') = 'array'
              AND EXISTS (
                  SELECT 1
                  FROM jsonb_array_elements(td.draft->'tasks') AS task,
                       jsonb_array_elements(task->'conditions') AS cond,
                       jsonb_array_elements(cond->'rules') AS rule,
                       jsonb_array_elements(rule->'predicates') AS pred
                  WHERE (pred->>'operator') = 'completed'
                    AND (pred->>'field_type') = 'task'
              )
        """)
    ]
