# Generated by Django 2.2 on 2026-06-23 16:49

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0254_add_fieldsets'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fieldsettemplate',
            name='fieldsettemplate_api_name_template_unique',
        ),
        migrations.AddField(
            model_name='fieldset',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fieldsettemplate',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldsettemplate',
            name='kickoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='processes.Kickoff'),
        ),
        migrations.AddField(
            model_name='fieldsettemplate',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldsettemplate',
            name='shared_fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_fieldsets', to='processes.FieldsetTemplate'),
        ),
        migrations.AddField(
            model_name='fieldsettemplate',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='processes.TaskTemplate'),
        ),
        migrations.AddField(
            model_name='fieldsettemplate',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fieldsettemplate',
            name='kickoffs',
            field=models.ManyToManyField(blank=True, related_name='old_fieldsets', through='processes.FieldsetTemplateKickoff', to='processes.Kickoff'),
        ),
        migrations.AlterField(
            model_name='fieldsettemplate',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='old_fieldsets', through='processes.FieldsetTemplateTaskTemplate', to='processes.TaskTemplate'),
        ),
        migrations.AlterField(
            model_name='fieldsettemplate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='processes.Template'),
        ),
        migrations.AlterField(
            model_name='fieldtemplateselection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='processes.Template'),
        ),
        migrations.AddConstraint(
            model_name='fieldsettemplate',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('api_name', 'template', 'is_shared'), name='fieldsettemplate_api_name_template_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldsettemplaterule',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_deleted=False),
                fields=('api_name', 'fieldset'),
                name='fieldsettemplate_rule_api_name_template_unique',
            ),
        ),
    ]
