# Generated by Django 2.2 on 2026-07-08 03:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0254_add_fileattachment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawperformer',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('group', 'group'), ('workflow_starter', 'workflow_starter'), ('field', 'field'), ('manager', 'manager')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rawperformertemplate',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('group', 'group'), ('workflow_starter', 'workflow_starter'), ('field', 'field'), ('manager', 'manager')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='parents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text='Api names of task parents', size=None),
        ),
        migrations.AlterField(
            model_name='taskperformer',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('group', 'group'), ('workflow_starter', 'workflow_starter'), ('field', 'field'), ('manager', 'manager')], default='user', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='taskperformer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='taskperformer',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_deleted=False),
                fields=('task', 'user', 'type'),
                name='processes_taskperformer_user_id_task_id_type_unique'),
        ),
    ]
