# Generated by Django 2.2 on 2026-06-23 16:49
# ruff: noqa: T201 BLE001
# Split from 0255 to avoid PostgreSQL error:
# "cannot CREATE INDEX because it has pending trigger events"
# Partial indexes (UniqueConstraint with condition) must be committed in their
# own transaction before the data migration runs.

from django.contrib.auth import get_user_model
from django.db import migrations, transaction


def get_drafts_by_fieldsets(TemplateDraft):
    """
    Returns a dict: {fieldset_api_name: set of TemplateDraft IDs}
    """
    result = {}
    for draft_obj in TemplateDraft.objects.all():
        draft = draft_obj.draft
        if not isinstance(draft, dict):
            continue

        # Process tasks -> fieldsets
        for task in draft.get('tasks') or []:
            for fieldset in task.get('fieldsets') or []:
                if isinstance(fieldset, dict):
                    api_name = fieldset.get('api_name')
                    if api_name:
                        result.setdefault(api_name, set())
                        result[api_name].add(draft_obj.id)

        # Process kickoff -> fieldsets
        kickoff = draft.get('kickoff')
        if isinstance(kickoff, dict):
            for fieldset in kickoff.get('fieldsets') or []:
                if isinstance(fieldset, dict):
                    api_name = fieldset.get('api_name')
                    if api_name:
                        result.setdefault(api_name, set())
                        result[api_name].add(draft_obj.id)

    return result


def update_draft_fieldset(TemplateDraft, draft_id, fieldset_data,
                          fieldset_api_name, shared_fieldset_id):
    draft_obj = TemplateDraft.objects.get(id=draft_id)
    draft = draft_obj.draft
    if not isinstance(draft, dict):
        return

    updated = False

    # Update matching fieldsets in tasks
    for task in draft.get('tasks') or []:
        for fieldset in task.get('fieldsets') or []:
            if fieldset.get('api_name') == fieldset_api_name:
                fieldset.update(fieldset_data)
                fieldset['shared_fieldset_id'] = shared_fieldset_id
                updated = True
                print(
                    f'*** Draft {draft_id} '
                    f'(template {draft_obj.draft["name"]})'
                    f' - task "{task.get("name", "?")}"'
                    f' - fieldset "{fieldset_data["name"]}" updated',
                )

    # Update matching fieldsets in kickoff
    kickoff = draft.get('kickoff')
    if isinstance(kickoff, dict):
        for fieldset in kickoff.get('fieldsets') or []:
            if fieldset.get('api_name') == fieldset_api_name:
                fieldset.update(fieldset_data)
                fieldset['shared_fieldset_id'] = shared_fieldset_id
                updated = True
                print(
                    f'*** Draft {draft_id} '
                    f'(template {draft_obj.draft["name"]})'
                    f' - kickoff'
                    f' - fieldset "{fieldset_data["name"]}" updated',
                )

    if updated:
        draft_obj.save(update_fields=('draft',))
        print(f'  Draft {draft_id} saved')


def migrate_shared_fieldsets(apps, schema_editor):
    FieldsetTemplate = apps.get_model('processes', 'FieldsetTemplate')
    TemplateDraft = apps.get_model('processes', 'TemplateDraft')
    FieldSetTemplateService = __import__(
        'src.processes.services.fieldsets.fieldset',
        fromlist=['FieldSetTemplateService'],
    ).FieldSetTemplateService

    drafts_by_old_fieldsets = get_drafts_by_fieldsets(TemplateDraft)
    old_fieldsets = (
        FieldsetTemplate.objects
        .filter(is_shared=True)
        .order_by('account_id')
    )
    with transaction.atomic():
        for old_fieldset in old_fieldsets:
            # Ensure the original is marked as shared
            old_fieldset.template_id = None
            old_fieldset.is_shared = True

            # Build the serialized representation of the shared fieldset
            fieldset_data = FieldSetTemplateService.to_json(old_fieldset)
            fieldset_data.pop('id')
            fieldset_data.pop('api_name')
            fieldset_data.pop('order')
            shared_fieldset_data = (
                FieldSetTemplateService._replace_api_names(fieldset_data)
            )
            old_fieldset.fields.all().delete()
            old_fieldset.rules.all().delete()
            UserModel = get_user_model()
            user = UserModel.objects.get(
                account_id=old_fieldset.account_id,
                is_account_owner=True,
            )
            shared_service = FieldSetTemplateService(user=user)
            shared_fieldset = shared_service.create(
                is_shared=True,
                **shared_fieldset_data,
            )
            print(
                f'Shared - {shared_fieldset.name} : {shared_fieldset.id}',
            )

            # Update drafts
            for draft_id in drafts_by_old_fieldsets.get(
                old_fieldset.api_name, [],
            ):
                update_draft_fieldset(
                    TemplateDraft=TemplateDraft,
                    draft_id=draft_id,
                    fieldset_data=fieldset_data,
                    fieldset_api_name=old_fieldset.api_name,
                    shared_fieldset_id=shared_fieldset.id,
                )

            kickoff_links = old_fieldset.kickoffs.through.objects.filter(
                fieldset=old_fieldset,
                is_deleted=False,
            )
            for link in kickoff_links:
                if not FieldsetTemplate.objects.filter(
                    shared_fieldset_id=shared_fieldset.id,
                    is_shared=False,
                    kickoff_id=link.kickoff_id,
                ).exists():
                    service = FieldSetTemplateService(user=user)
                    new_fs = service.create(
                        **fieldset_data,
                        is_shared=False,
                        shared_fieldset_id=shared_fieldset.id,
                        order=link.order,
                        kickoff_id=link.kickoff_id,
                        template_id=link.kickoff.template_id,
                    )
                    print(
                        f'+++ {link.kickoff.template.name} : '
                        f'{link.kickoff.template_id} - '
                        f'{new_fs.name} : {new_fs.id}',
                    )
                link.delete()

            task_links = old_fieldset.tasks.through.objects.filter(
                fieldset=old_fieldset,
                is_deleted=False,
            )
            for link in task_links:
                if not FieldsetTemplate.objects.filter(
                    shared_fieldset_id=shared_fieldset.id,
                    is_shared=False,
                    task_id=link.task_id,
                ).exists():
                    service = FieldSetTemplateService(user=user)
                    try:
                        new_fs = service.create(
                            **fieldset_data,
                            is_shared=False,
                            shared_fieldset_id=shared_fieldset.id,
                            order=link.order,
                            task_id=link.task_id,
                            template_id=link.task.template_id,
                        )
                        print(
                            f'+++ {link.task.template.name} : '
                            f'{link.task.template_id} - '
                            f'{new_fs.name} : {new_fs.id}',
                        )
                    except Exception:
                        print(
                            f'--- Duplicate '
                            f'{link.task.template.name} : '
                            f'{link.task.template_id}',
                        )
                link.delete()
            old_fieldset.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0255_add_shared_fieldsets'),
    ]

    operations = [
        migrations.RunPython(
            migrate_shared_fieldsets,
            migrations.RunPython.noop,
        ),
    ]
