# Generated by Django 2.2 on 2026-07-22 12:57
# Manually pruned: makemigrations also emitted operations for
# pre-existing model/migration drift unrelated to AI performers
# (FileAttachment/SearchContent removal, task.parents help_text);
# only the AI-performer operations are kept here.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_auto_20260722_1257'),
        ('processes', '0255_add_fieldsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawperformer',
            name='ai_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.AIAgent'),
        ),
        migrations.AddField(
            model_name='rawperformertemplate',
            name='ai_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.AIAgent'),
        ),
        migrations.AddField(
            model_name='taskperformer',
            name='ai_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.AIAgent'),
        ),
        migrations.AlterField(
            model_name='rawperformer',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('group', 'group'), ('workflow_starter', 'workflow_starter'), ('field', 'field'), ('manager', 'manager'), ('ai_agent', 'ai_agent')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rawperformertemplate',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('group', 'group'), ('workflow_starter', 'workflow_starter'), ('field', 'field'), ('manager', 'manager'), ('ai_agent', 'ai_agent')], max_length=100),
        ),
        migrations.AlterField(
            model_name='taskperformer',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('group', 'group'), ('workflow_starter', 'workflow_starter'), ('field', 'field'), ('manager', 'manager'), ('ai_agent', 'ai_agent')], default='user', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='taskperformer',
            constraint=models.UniqueConstraint(condition=models.Q(('ai_agent__isnull', False), ('is_deleted', False)), fields=('ai_agent', 'task'), name='taskperformer_ai_agent_task_unique'),
        ),
    ]
