# Generated by Django 2.2 on 2026-08-04 22:36

from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0145_auto_20260804_2236'),
        ('processes', '0258_rebuild_attachment_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSetTemplateRuleGroupAnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('operator', models.CharField(choices=[('sum_equal', 'Sum equal'), ('sum_greater_than', 'Sum greater than'), ('sum_less_than', 'Sum less than')], max_length=50)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldSetTemplateRuleGroupOr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldSetTemplateRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('sum_equal', 'The sum is equal'), ('validator', 'Validator')], max_length=50)),
                ('message', models.TextField(blank=True, help_text='custom error message for a type="validator"', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldTemplateRuleGroupAnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('operator', models.CharField(choices=[('equal', 'Equal'), ('greater_than', 'Greater than'), ('less_than', 'Less than')], max_length=50)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('field', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldTemplateRuleGroupOr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldTemplateRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('show', 'Show field'), ('validator', 'Validate field')], max_length=50)),
                ('message', models.TextField(blank=True, help_text='custom error message for a type="validator"', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='fieldsettemplate',
            name='fieldsettemplate_template_api_name_is_shared_unique',
        ),
        migrations.RemoveConstraint(
            model_name='fieldtemplate',
            name='processes_fieldtemplate_template_api_name_unique',
        ),

        migrations.AlterField(
            model_name='fieldsetrule',
            name='type',
            field=models.CharField(choices=[('sum_equal', 'The sum is equal'), ('validator', 'Validator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldsettemplaterule',
            name='type',
            field=models.CharField(choices=[('sum_equal', 'The sum is equal'), ('validator', 'Validator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='type',
            field=models.IntegerField(choices=[(0, 'Workflow started'), (1, 'Workflow completed'), (2, 'Task started'), (3, 'Task completed'), (4, 'Task reverted'), (9, 'Task skipped'), (5, 'New comment'), (6, 'Workflow ended'), (7, 'Workflow snoozed from template'), (17, 'Workflow snoozed'), (8, 'Workflow reverted'), (10, 'Workflow ended by condition'), (11, 'Workflow is urgent'), (12, 'Workflow is not urgent'), (13, 'Task skipped as no performers were assigned'), (14, 'Performer added to task'), (15, 'Performer deleted from task'), (16, 'Workflow resumed'), (18, 'Due date changed'), (20, 'Performer group added to task'), (21, 'Performer group deleted from task'), (22, 'Task snoozed from template'), (23, 'Task delegated')], verbose_name='type'),
        ),
        migrations.AddConstraint(
            model_name='fieldsettemplate',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('api_name', 'template', 'is_shared', 'account'), name='fieldsettemplate_template_api_name_is_shared_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('template', 'api_name', 'account'), name='processes_fieldtemplate_template_api_name_unique'),
        ),
        migrations.AddField(
            model_name='fieldtemplateruleset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldtemplateruleset',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='processes.FieldTemplate'),
        ),
        migrations.AddField(
            model_name='fieldtemplateruleset',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_rulesets', to='processes.Template'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupor',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupor',
            name='field_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_or', to='processes.FieldTemplateRuleSet'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupor',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_ruleset_groups_or', to='processes.Template'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupand',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupand',
            name='group_or',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_and', to='processes.FieldTemplateRuleGroupOr'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupand',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_rules_group_and', to='processes.Template'),
        ),
        migrations.AddField(
            model_name='fieldsettemplateruleset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldsettemplateruleset',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='fieldset_rulesets', to='processes.FieldTemplate'),
        ),
        migrations.AddField(
            model_name='fieldsettemplateruleset',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='processes.FieldsetTemplate'),
        ),
        migrations.AddField(
            model_name='fieldsettemplateruleset',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_rulesets', to='processes.Template'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupor',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupor',
            name='fieldset_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_or', to='processes.FieldSetTemplateRuleSet'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupor',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_ruleset_groups_or', to='processes.Template'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupand',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupand',
            name='group_or',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_and', to='processes.FieldSetTemplateRuleGroupOr'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupand',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_rules_group_and', to='processes.Template'),
        ),
        migrations.AddConstraint(
            model_name='fieldtemplateruleset',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('template', 'api_name', 'account'), name='fieldtemplateruleset_field_api_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldtemplaterulegroupor',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('api_name', 'template', 'account'), name='rulegroupor_field_rule_api_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldtemplaterulegroupand',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('template', 'api_name', 'account'), name='rulegroupand_group_or_api_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldsettemplateruleset',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('template', 'api_name', 'account'), name='fieldsetruleset_fieldset_api_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldsettemplaterulegroupor',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('api_name', 'template', 'account'), name='fieldset_rulegroupor_field_rule_api_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldsettemplaterulegroupand',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('template', 'api_name', 'account'), name='fieldset_rulegroupand_group_or_api_name_unique'),
        ),
    ]
