# Generated by Django 2.2.28 on 2026-08-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0258_rebuild_attachment_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='status_updated',
        ),
    ]
