# Generated by Django 5.2.17 on 2026-10-03 06:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0259_populate_fieldset_title_from_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtemplate',
            name='template',
            field=models.JSONField(blank=True, help_text='<span style="float: right; line-height: 18px; font-size: 15px; color: #4C4C4C">If you want to pass default args to kickoff fields, add default parameter to field template like this: `"default": "account_name"`. <br>If you want to make generic name, you should add parameter "generic_name" like this: `"generic_name": "{{user_first_name}}\'s onboarding".<br>Possible dynamic values: account_name, user_first_name, user_last_name, user_email</span>', null=True),
        ),
        migrations.AlterField(
            model_name='systemworkflowkickoffdata',
            name='kickoff_data',
            field=models.JSONField(blank=True, help_text='<span style="float: right; line-height: 18px; font-size: 15px; color: #4C4C4C">You can use template vars: <b>account_name, user_first_name, user_last_name, user_email</b></br>Example: Onboarding {{ user_first_name }} {{ user_first_name }}</span>', null=True),
        ),
        migrations.AlterField(
            model_name='templatedraft',
            name='draft',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templateversion',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='delay_json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='task_json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='watched',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
