# Generated by Django 2.2 on 2026-08-14 20:03
from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models


def migrate_fieldset_template_rules(apps, schema_editor):
    OldRule = apps.get_model('processes', 'FieldsetTemplateRule')
    RuleSet = apps.get_model('processes', 'FieldSetTemplateRuleSet')
    GroupOr = apps.get_model(
        'processes', 'FieldSetTemplateRuleGroupOr',
    )
    GroupAnd = apps.get_model(
        'processes', 'FieldSetTemplateRuleGroupAnd',
    )

    order_by_fieldset = {}
    rules = (
        OldRule.objects
        .select_related('fieldset')
        .prefetch_related('fields')
        .order_by('fieldset_id', 'id')
    )
    for rule in rules:
        if RuleSet.objects.filter(
            fieldset_id=rule.fieldset_id,
            api_name=rule.api_name,
        ).exists():
            continue

        order_in_fieldset = order_by_fieldset.get(
            rule.fieldset_id, 0,
        )
        order_by_fieldset[rule.fieldset_id] = (
            order_in_fieldset + 1
        )
        template_id = rule.fieldset.template_id

        ruleset = RuleSet.objects.create(
            api_name=rule.api_name,
            message=None,
            order=order_in_fieldset,
            fieldset_id=rule.fieldset_id,
            template_id=template_id,
            account_id=rule.account_id,
        )
        group_or = GroupOr.objects.create(
            api_name=f'{rule.api_name}-group-or',
            fieldset_rule=ruleset,
            template_id=template_id,
            account_id=rule.account_id,
        )
        GroupAnd.objects.create(
            api_name=f'{rule.api_name}-group-and',
            group_or=group_or,
            template_id=template_id,
            account_id=rule.account_id,
            operator=rule.type,
            value=rule.value,
        )
        ruleset.fields.set(rule.fields.all())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0146_auto_20260814_2002'),
        ('processes', '0259_populate_fieldset_title_from_name'),
    ]

    operations = [
        # CreateModel — template models
        migrations.CreateModel(
            name='FieldSetTemplateRuleGroupAnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('operator', models.CharField(choices=[('sum_equal', 'Sum equal'), ('sum_greater_than', 'Sum greater than'), ('sum_less_than', 'Sum less than')], max_length=50)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldSetTemplateRuleGroupOr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldSetTemplateRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, help_text='custom error message for a type="validator"', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldTemplateRuleGroupAnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('operator', models.CharField(choices=[('equal', 'Equal'), ('greater_than', 'Greater than'), ('less_than', 'Less than')], max_length=50)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('field', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldTemplateRuleGroupOr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldTemplateRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('show', 'Show field'), ('validator', 'Validate field')], max_length=50)),
                ('message', models.TextField(blank=True, help_text='custom error message for a type="validator"', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),

        # AddField — FieldTemplateRuleSet
        migrations.AddField(
            model_name='fieldtemplateruleset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldtemplateruleset',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='processes.FieldTemplate'),
        ),
        migrations.AddField(
            model_name='fieldtemplateruleset',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_rulesets', to='processes.Template'),
        ),
        migrations.AddField(
            model_name='fieldtemplateruleset',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),

        # AddField — FieldTemplateRuleGroupOr
        migrations.AddField(
            model_name='fieldtemplaterulegroupor',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupor',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_or', to='processes.FieldTemplateRuleSet'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupor',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_ruleset_groups_or', to='processes.Template'),
        ),

        # AddField — FieldTemplateRuleGroupAnd
        migrations.AddField(
            model_name='fieldtemplaterulegroupand',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupand',
            name='group_or',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_and', to='processes.FieldTemplateRuleGroupOr'),
        ),
        migrations.AddField(
            model_name='fieldtemplaterulegroupand',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_rules_group_and', to='processes.Template'),
        ),

        # AddField — FieldSetTemplateRuleSet
        migrations.AddField(
            model_name='fieldsettemplateruleset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldsettemplateruleset',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='fieldset_rulesets', to='processes.FieldTemplate'),
        ),
        migrations.AddField(
            model_name='fieldsettemplateruleset',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='processes.FieldsetTemplate'),
        ),
        migrations.AddField(
            model_name='fieldsettemplateruleset',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_rulesets', to='processes.Template'),
        ),

        # AddField — FieldSetTemplateRuleGroupOr
        migrations.AddField(
            model_name='fieldsettemplaterulegroupor',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupor',
            name='fieldset_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_or', to='processes.FieldSetTemplateRuleSet'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupor',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_ruleset_groups_or', to='processes.Template'),
        ),

        # AddField — FieldSetTemplateRuleGroupAnd
        migrations.AddField(
            model_name='fieldsettemplaterulegroupand',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupand',
            name='group_or',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_and', to='processes.FieldSetTemplateRuleGroupOr'),
        ),
        migrations.AddField(
            model_name='fieldsettemplaterulegroupand',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_rules_group_and', to='processes.Template'),
        ),

        # RunPython — data migration
        migrations.RunPython(
            migrate_fieldset_template_rules,
            migrations.RunPython.noop,
            elidable=False,
        ),

        # RemoveConstraint — old constraints
        migrations.RemoveConstraint(
            model_name='fieldsettemplate',
            name='fieldsettemplate_template_api_name_is_shared_unique',
        ),
        migrations.RemoveConstraint(
            model_name='fieldtemplate',
            name='processes_fieldtemplate_template_api_name_unique',
        ),

        # AddConstraint — re-add on old models
        migrations.AddConstraint(
            model_name='fieldsettemplate',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('api_name', 'template', 'is_shared', 'account'), name='fieldsettemplate_template_api_name_is_shared_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('template', 'api_name', 'account'), name='processes_fieldtemplate_template_api_name_unique'),
        ),

        # Raw SQL — NULLS NOT DISTINCT unique indexes (PostgreSQL 15+)
        # Django 2.2 cannot express NULLS NOT DISTINCT via ORM.
        # Only (parent_fk, api_name) — template_id and account_id
        # are redundant because they are determined by the parent FK.
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX fieldtemplateruleset_field_api_name_unique ON processes_fieldtemplateruleset (field_id, api_name) NULLS NOT DISTINCT WHERE NOT is_deleted',
            reverse_sql='DROP INDEX IF EXISTS fieldtemplateruleset_field_api_name_unique',
        ),
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX rulegroupor_field_rule_api_name_unique ON processes_fieldtemplaterulegroupor (ruleset_id, api_name) NULLS NOT DISTINCT WHERE NOT is_deleted',
            reverse_sql='DROP INDEX IF EXISTS rulegroupor_field_rule_api_name_unique',
        ),
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX rulegroupand_group_or_api_name_unique ON processes_fieldtemplaterulegroupand (group_or_id, api_name) NULLS NOT DISTINCT WHERE NOT is_deleted',
            reverse_sql='DROP INDEX IF EXISTS rulegroupand_group_or_api_name_unique',
        ),
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX fieldsetruleset_fieldset_api_name_unique ON processes_fieldsettemplateruleset (fieldset_id, api_name) NULLS NOT DISTINCT WHERE NOT is_deleted',
            reverse_sql='DROP INDEX IF EXISTS fieldsetruleset_fieldset_api_name_unique',
        ),
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX fieldset_rulegroupor_field_rule_api_name_unique ON processes_fieldsettemplaterulegroupor (fieldset_rule_id, api_name) NULLS NOT DISTINCT WHERE NOT is_deleted',
            reverse_sql='DROP INDEX IF EXISTS fieldset_rulegroupor_field_rule_api_name_unique',
        ),
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX fieldset_rulegroupand_group_or_api_name_unique ON processes_fieldsettemplaterulegroupand (group_or_id, api_name) NULLS NOT DISTINCT WHERE NOT is_deleted',
            reverse_sql='DROP INDEX IF EXISTS fieldset_rulegroupand_group_or_api_name_unique',
        ),

        # AlterField — template models
        migrations.AlterField(
            model_name='fieldsettemplaterule',
            name='type',
            field=models.CharField(choices=[('sum_equal', 'Sum equal'), ('validator', 'Validator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldtemplaterulegroupand',
            name='operator',
            field=models.CharField(choices=[('equal', 'Equal'), ('not_equals', 'Not equal'), ('exists', 'Exists'), ('not_exists', 'Not exists'), ('greater_than', 'Greater than'), ('less_than', 'Less than'), ('contains', 'Contains'), ('not_contains', 'Not contains')], max_length=50),
        ),
    ]
