# Generated by Django 2.2.28 on 2026-09-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0259_populate_fieldset_title_from_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowevent',
            name='type',
            field=models.IntegerField(
                choices=[
                    (0, 'Workflow started'),
                    (1, 'Workflow completed'),
                    (2, 'Task started'),
                    (3, 'Task completed'),
                    (4, 'Task reverted'),
                    (9, 'Task skipped'),
                    (5, 'New comment'),
                    (6, 'Workflow ended'),
                    (7, 'Workflow snoozed from template'),
                    (17, 'Workflow snoozed'),
                    (8, 'Workflow reverted'),
                    (10, 'Workflow ended by condition'),
                    (11, 'Workflow is urgent'),
                    (12, 'Workflow is not urgent'),
                    (13, 'Task skipped as no performers were assigned'),
                    (14, 'Performer added to task'),
                    (15, 'Performer deleted from task'),
                    (16, 'Workflow resumed'),
                    (18, 'Due date changed'),
                    (19, 'Sub-workflow started'),
                    (20, 'Performer group added to task'),
                    (21, 'Performer group deleted from task'),
                    (22, 'Task snoozed from template'),
                    (23, 'Task delegated'),
                ],
                verbose_name='type',
            ),
        ),
    ]
