# Generated by Django 2.2 on 2026-08-14 20:03
from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0260_add_template_rulesets'),
    ]

    operations = [
        # CreateModel — runtime models
        migrations.CreateModel(
            name='FieldRuleGroupAnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('operator', models.CharField(choices=[('equal', 'Equal'), ('greater_than', 'Greater than'), ('less_than', 'Less than')], max_length=50)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('field', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldRuleGroupOr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('show', 'Show field'), ('validator', 'Validate field')], max_length=50)),
                ('message', models.TextField(blank=True, help_text='custom error message for a type="validator"', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldSetRuleGroupAnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('operator', models.CharField(choices=[('sum_equal', 'Sum equal'), ('sum_greater_than', 'Sum greater than'), ('sum_less_than', 'Sum less than')], max_length=50)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldSetRuleGroupOr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldSetRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, help_text='custom error message for a type="validator"', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),

        # AddField — FieldSetRuleSet
        migrations.AddField(
            model_name='fieldsetruleset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldsetruleset',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='fieldset_rulesets', to='processes.TaskField'),
        ),
        migrations.AddField(
            model_name='fieldsetruleset',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='processes.FieldSet'),
        ),
        migrations.AddField(
            model_name='fieldsetruleset',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_rulesets', to='processes.Workflow'),
        ),

        # AddField — FieldSetRuleGroupOr
        migrations.AddField(
            model_name='fieldsetrulegroupor',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldsetrulegroupor',
            name='fieldset_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_or', to='processes.FieldSetRuleSet'),
        ),
        migrations.AddField(
            model_name='fieldsetrulegroupor',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_ruleset_groups_or', to='processes.Workflow'),
        ),

        # AddField — FieldSetRuleGroupAnd
        migrations.AddField(
            model_name='fieldsetrulegroupand',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldsetrulegroupand',
            name='group_or',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_and', to='processes.FieldSetRuleGroupOr'),
        ),
        migrations.AddField(
            model_name='fieldsetrulegroupand',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_rules_group_and', to='processes.Workflow'),
        ),

        # AddField — FieldRuleSet
        migrations.AddField(
            model_name='fieldruleset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldruleset',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='processes.TaskField'),
        ),
        migrations.AddField(
            model_name='fieldruleset',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rulesets', to='processes.Workflow'),
        ),
        migrations.AddField(
            model_name='fieldruleset',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),

        # AddField — FieldRuleGroupOr
        migrations.AddField(
            model_name='fieldrulegroupor',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldrulegroupor',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_or', to='processes.FieldRuleSet'),
        ),
        migrations.AddField(
            model_name='fieldrulegroupor',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_ruleset_groups_or', to='processes.Workflow'),
        ),

        # AddField — FieldRuleGroupAnd
        migrations.AddField(
            model_name='fieldrulegroupand',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='fieldrulegroupand',
            name='group_or',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_and', to='processes.FieldRuleGroupOr'),
        ),
        migrations.AddField(
            model_name='fieldrulegroupand',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rules_group_and', to='processes.Workflow'),
        ),

        # AlterField — runtime models
        migrations.AlterField(
            model_name='fieldrulegroupand',
            name='operator',
            field=models.CharField(choices=[('equal', 'Equal'), ('not_equals', 'Not equal'), ('exists', 'Exists'), ('not_exists', 'Not exists'), ('greater_than', 'Greater than'), ('less_than', 'Less than'), ('contains', 'Contains'), ('not_contains', 'Not contains')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldsetrule',
            name='type',
            field=models.CharField(choices=[('sum_equal', 'Sum equal'), ('validator', 'Validator')], max_length=50),
        ),
    ]
