"""Ensure no sensitive fields leak into public response schemas."""

import pytest
from drf_spectacular.generators import SchemaGenerator

pytestmark = pytest.mark.django_db

_SENSITIVE_PATTERNS = frozenset({
    'password', 'passwd', 'pwd',
    'new_password', 'old_password', 'confirm_new_password',
    'secret', 'secret_key',
    'api_key', 'apikey',
    'private_key',
    'credit_card', 'card_number', 'cvv', 'ssn',
})

_ALLOWED = frozenset({
    ('AuthTokenResponse', 'token'),
    # write_only=True fields that drf-spectacular still
    # includes in the shared component schema; the actual
    # API never returns these — fix in serializer annotations.
    ('User', 'password'),
    ('UserPrivileges', 'password'),
    # Endpoint excluded via ExcludedPath, but the schema
    # component is still generated by drf-spectacular.
    ('UserAPIKey', 'api_key'),
})


def _collect_response_refs(paths: dict) -> set:
    """Collect all $ref schema names used in 2xx responses."""
    refs = set()
    for _path, operations in paths.items():
        for _method, operation in operations.items():
            if not isinstance(operation, dict):
                continue
            for status, response in (
                operation.get('responses') or {}
            ).items():
                if not status.startswith('2'):
                    continue
                _walk_refs(response, refs)
    return refs


def _walk_refs(node: dict, refs: set) -> None:
    if not isinstance(node, dict):
        return
    ref = node.get('$ref')
    if ref and ref.startswith('#/components/schemas/'):
        refs.add(ref.split('/')[-1])
    for key in ('schema', 'items', 'content'):
        child = node.get(key)
        if isinstance(child, dict):
            _walk_refs(child, refs)
    for media in (
        node.get('content') or {}
    ).values():
        if isinstance(media, dict):
            _walk_refs(media, refs)
    for composite in ('allOf', 'oneOf', 'anyOf'):
        for item in node.get(composite) or []:
            _walk_refs(item, refs)


def _expand_nested_refs(
    schema_name: str,
    schemas: dict,
    visited: set,
) -> set:
    """Recursively collect schema names referenced by properties."""
    if schema_name in visited:
        return set()
    visited.add(schema_name)
    result = {schema_name}
    schema = schemas.get(schema_name, {})
    for prop in (schema.get('properties') or {}).values():
        _collect_schema_refs(prop, schemas, visited, result)
    for composite in ('allOf', 'oneOf', 'anyOf'):
        for item in schema.get(composite) or []:
            _collect_schema_refs(
                item, schemas, visited, result,
            )
    return result


def _collect_schema_refs(
    node: dict,
    schemas: dict,
    visited: set,
    result: set,
) -> None:
    if not isinstance(node, dict):
        return
    ref = node.get('$ref')
    if ref and ref.startswith('#/components/schemas/'):
        name = ref.split('/')[-1]
        result |= _expand_nested_refs(
            name, schemas, visited,
        )
    child = node.get('items')
    if isinstance(child, dict):
        _collect_schema_refs(
            child, schemas, visited, result,
        )
    for composite in ('allOf', 'oneOf', 'anyOf'):
        for item in node.get(composite) or []:
            _collect_schema_refs(
                item, schemas, visited, result,
            )


def test_response_schemas__sensitive_fields__absent():
    """Fail when a response schema exposes a sensitive field.

    Generates the full OpenAPI schema, collects every
    component referenced by 2xx responses (recursively),
    and checks property names against _SENSITIVE_PATTERNS.
    """

    # arrange
    generator = SchemaGenerator()
    schema = generator.get_schema(request=None, public=True)
    paths = schema.get('paths') or {}
    schemas = (
        schema.get('components', {}).get('schemas') or {}
    )

    response_refs = _collect_response_refs(paths)
    all_response_schemas = set()
    for ref_name in response_refs:
        all_response_schemas |= _expand_nested_refs(
            ref_name, schemas, set(),
        )

    # act
    violations = []
    for schema_name in sorted(all_response_schemas):
        props = (
            schemas.get(schema_name, {})
            .get('properties') or {}
        )
        for field_name in props:
            if field_name.lower() in _SENSITIVE_PATTERNS:
                pair = (schema_name, field_name)
                if pair not in _ALLOWED:
                    violations.append(
                        f'{schema_name}.{field_name}',
                    )

    # assert
    assert violations == [], (
        'Sensitive fields found in response schemas:\n'
        + '\n'.join(f'  - {v}' for v in violations)
    )
