# Generated by Django 2.2 on 2026-02-03 08:00

from django.db import migrations, models
import django.db.models.deletion
import src.generics.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0139_remove_account_external_id'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('file_id', models.CharField(db_index=True, help_text='File identifier in the file service', max_length=512)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('account', 'Account'), ('restricted', 'Restricted')], default='account', help_text='File access type', max_length=20)),
                ('source_type', models.CharField(choices=[('Account', 'Account'), ('Workflow', 'Workflow'), ('Task', 'Task'), ('Template', 'Template')], help_text='File source type', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_attachments', to='processes.WorkflowEvent')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_attachments', to='processes.TaskField')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_attachments', to='processes.Task')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_attachments', to='processes.Template')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_attachments', to='processes.Workflow')),
            ],
            options={
                'permissions': (('access_attachment', 'Can access attachment'),),
            },
            bases=(src.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['source_type', 'account'], name='storage_att_source__a020ca_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['is_deleted', 'access_type', 'account'], name='storage_att_del_acc_type_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['is_deleted', 'access_type'], name='storage_att_del_acc_idx'),
        ),
        # Scoped uniqueness: one file_id per entity (scope).
        # Django ORM UniqueConstraint does not support NULLS NOT DISTINCT,
        # so we use raw SQL (same pattern as processes_search_content_unique).
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX storage_attachment_scoped_unique
                ON storage_attachment (
                    file_id, template_id, task_id,
                    workflow_id, event_id, output_id
                )
                NULLS NOT DISTINCT
                WHERE is_deleted = FALSE;
            """,
        ),
    ]
