# Generated by Django 2.2 on 2024-08-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountevent',
            name='direction',
            field=models.CharField(choices=[('received', 'received'), ('sent', 'sent')], default='received', max_length=100),
        ),
    ]
