# Generated by Django 2.2 on 2024-08-20 19:52
from django.db.models.deletion import CASCADE
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_accountevent_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountevent',
            name='account',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=CASCADE,
                to='accounts.Account'
            ),
        ),
    ]
