# Generated by Django 2.2 on 2024-08-09 11:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import pneumatic_backend.generics.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0123_account_log_api_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('error', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=50, null=True)),
                ('scheme', models.CharField(blank=True, max_length=50, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('api', 'api'), ('databus', 'databus')], default='api', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created', 'account'),
            },
            bases=(pneumatic_backend.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
    ]
