# Generated by Django 2.2.5 on 2019-10-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='registered',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
