# Generated by Django 2.2.5 on 2019-10-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_googleauth_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAuth',
        ),
    ]
