# Generated by Django 2.2.5 on 2019-10-03 09:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_googleauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_staff', models.BooleanField(default=False, verbose_name="Should the user be admin (user's is_staff property)")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
