# Generated by Django 2.2.5 on 2019-10-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191003_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='userinvite',
            options={'verbose_name': 'User Invite'},
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
