# Generated by Django 2.2.6 on 2019-10-15 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191009_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+99999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
