# Generated by Django 2.2.5 on 2019-10-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191015_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ab_id',
            field=models.IntegerField(default=0),
        ),
    ]
