# Generated by Django 2.2.6 on 2019-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_ab_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_onboarding_finished',
            field=models.BooleanField(default=False),
        ),
    ]
