# Generated by Django 2.2.5 on 2019-10-31 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userinvite_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+99999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
