# Generated by Django 2.2.7 on 2019-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='applications',
            field=models.ManyToManyField(to='applications.Application', verbose_name='Account applications'),
        ),
    ]
