# Generated by Django 2.2.7 on 2019-11-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191111_0912'),
        ('accounts', '0015_auto_20191108_0656'),
    ]

    operations = [
    ]
