# Generated by Django 2.2.7 on 2019-11-25 10:37

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20191111_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearBitUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearbit', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
