# Generated by Django 2.2.10 on 2020-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200211_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_users',
            field=models.IntegerField(default=1),
        ),
    ]
