# Generated by Django 2.2.10 on 2020-02-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_account_total_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_users',
            field=models.IntegerField(default=1),
        ),
    ]
