# Generated by Django 2.2.10 on 2020-02-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_account_active_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_account_owner',
            field=models.BooleanField(default=False),
        ),
    ]
