# Generated by Django 2.2.10 on 2020-02-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_account_active_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('invited', 'invited'), ('active', 'active')], default='active', max_length=16),
        ),
    ]
