# Generated by Django 2.2.10 on 2020-02-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_is_account_owner'),
        ('accounts', '0026_user_status'),
    ]

    operations = [
    ]
