# Generated by Django 2.2.10 on 2020-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_merge_20200227_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_about_tasks',
            field=models.BooleanField(default=True),
        ),
    ]
