# Generated by Django 2.2.10 on 2020-03-17 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_user_notify_about_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
