# Generated by Django 2.2.11 on 2020-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200406_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='invited_from',
            field=models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('google', 'Google')], default='email', max_length=16),
        ),
    ]
