# Generated by Django 2.2.13 on 2020-06-23 16:50

from django.db import migrations


def create_througth_relations(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    AccountApplication = apps.get_model('accounts', 'AccountApplication')
    for account in Account.objects.all():
        for app in account.applications.all():
            AccountApplication.objects.create(
                account=account,
                application=app
            )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_accountapplication'),
    ]

    operations = [
        migrations.RunPython(create_througth_relations, reverse_code=migrations.RunPython.noop)
    ]
