# Generated by Django 2.2.13 on 2020-06-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20200623_1409'),
        ('accounts', '0039_remove_account_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='applications',
            field=models.ManyToManyField(related_name='account_apps', through='accounts.AccountApplication', to='applications.Application'),
        ),
    ]
