# Generated by Django 2.2.13 on 2020-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20200623_1409'),
        ('accounts', '0041_auto_20200623_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountApplication',
            new_name='AccountGenericWorkflows',
        ),
        migrations.RenameField(
            model_name='accountgenericworkflows',
            old_name='application',
            new_name='genericworkflow',
        ),
        migrations.AlterField(
            model_name='account',
            name='applications',
            field=models.ManyToManyField(related_name='account_generic_workflows', through='accounts.AccountGenericWorkflows', to='applications.Application'),
        ),
    ]
