# Generated by Django 2.2.14 on 2020-08-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20200730_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_digest_subscriber',
            field=models.BooleanField(default=True),
        ),
    ]
