# Generated by Django 2.2.15 on 2020-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20200818_1221'),
        ('processes', '0056_migrate_generic_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='templates',
        ),
        migrations.AlterField(
            model_name='account',
            name='applications',
            field=models.ManyToManyField(related_name='account_workflow_templates', through='accounts.AccountWorkflowTemplates', to='processes.WorkflowTemplate'),
        ),
    ]
