# Generated by Django 2.2.15 on 2020-08-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20200818_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountGenericWorkflows',
        ),
    ]
