# Generated by Django 2.2.16 on 2020-11-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20201020_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='applications',
            new_name='workflow_templates',
        ),
    ]
