# Generated by Django 2.2.16 on 2020-11-23 11:51

from django.db import migrations

from pneumatic_backend.authentication.tokens import PneumaticToken


def add_default_api_key(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    APIKey = apps.get_model('accounts', 'APIKey')
    api_key_list = []
    for account in Account.objects.filter(is_deleted=False):
        owner = account.get_owner()
        if owner:
            api_key_list.append(APIKey(
                account=account,
                user=owner,
                key=PneumaticToken.create(user=owner, for_api_key=True),
                name=owner.get_full_name(),
            ))
    APIKey.objects.bulk_create(api_key_list)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20201105_1238'),
    ]

    operations = [
        migrations.RunPython(add_default_api_key, reverse_code=migrations.RunPython.noop)
    ]
