# Generated by Django 2.2.16 on 2020-11-24 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20201123_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='invited_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcoming_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveConstraint(
            model_name='userinvite',
            name='user_invite_email_unique',
        ),
        migrations.AddConstraint(
            model_name='userinvite',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('account', 'invited_user'), name='accounts_userinvite_account_id_invited_user_id_unique'),
        ),
    ]
