# Generated by Django 2.2.16 on 2020-11-27 11:33
from django.db import migrations

from pneumatic_backend.authentication.tokens import PneumaticToken


def set_apikey_for_users(apps, schema_editor):
    APIKey = apps.get_model('accounts', 'APIKey')
    UserModel = apps.get_model('accounts', 'User')
    data_bulk = []
    for user in UserModel.objects.filter(
            is_robot=False,
            is_active=True,
            status='active'
    ):
        try:
            key = PneumaticToken.create(user, for_api_key=True)
        except ValueError:
            PneumaticToken.expire_all_tokens(user)
            key = PneumaticToken.create(user, for_api_key=True)
        data_bulk.append(
            APIKey(
                user_id=user.id,
                key=key,
                name=user.first_name,
                account_id=user.account_id,
            )
        )
    APIKey.objects.bulk_create(data_bulk)


def remove_apikeys_from_users(apps, schema_editor):
    UserModel = apps.get_model('accounts', 'User')
    for user in UserModel.objects.filter(
            is_robot=False,
            is_active=True,
            status='active'
    ):
        PneumaticToken.expire_token(user.apikey.key)
        user.apikey.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20201126_1312'),
    ]

    operations = [
        migrations.RunPython(set_apikey_for_users, reverse_code=remove_apikeys_from_users)
    ]
