# Generated by Django 2.2.17 on 2020-12-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20201124_1132'),
        ('accounts', '0059_auto_20201127_1133'),
    ]

    operations = [
    ]
