# Generated by Django 2.2.17 on 2020-12-10 09:29
from django.db import migrations


def update_users_tokens_with_dict(apps, schema_editor):
    pass


def update_users_tokens_with_tuple(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_merge_20201201_0934'),
    ]

    operations = [
        migrations.RunPython(update_users_tokens_with_dict, reverse_code=update_users_tokens_with_tuple),
    ]
