# Generated by Django 2.2.17 on 2020-12-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20201218_1227'),
        ('accounts', '0063_auto_20201218_1158'),
    ]

    operations = [
    ]
