# Generated by Django 2.2.17 on 2020-12-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_merge_20201221_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notified_about_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
