# Generated by Django 2.2.17 on 2021-02-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20210201_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_robot',
        ),
    ]
