# Generated by Django 2.2.17 on 2021-02-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_remove_user_is_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='max_users',
            field=models.IntegerField(default=5),
        ),
    ]
