# Generated by Django 2.2.17 on 2021-05-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_accountsignupdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='max_active_workflows',
            field=models.IntegerField(default=5),
        ),
    ]
