# Generated by Django 2.2.17 on 2021-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_account_max_active_workflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('invited', 'invited'), ('active', 'active'), ('inactive', 'inactive')], default='active', max_length=16),
        ),
    ]
