# Generated by Django 2.2.17 on 2021-05-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_auto_20210512_1009'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_email_unique',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='user_username_unique',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(_negated=True, status='inactive')), fields=('email',), name='user_email_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(_negated=True, status='inactive')), fields=('username',), name='user_username_unique'),
        ),
    ]
