# Generated by Django 2.2.17 on 2021-05-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0127_auto_20210511_1448'),
        ('accounts', '0073_auto_20210513_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='workflow_templates',
            field=models.ManyToManyField(related_name='account_system_template', through='accounts.AccountWorkflowTemplates', to='processes.SystemTemplate'),
        ),
    ]
