# Generated by Django 2.2.17 on 2021-05-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0127_auto_20210511_1448'),
        ('accounts', '0074_alter_model_20210512_0619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountWorkflowTemplates',
            new_name='AccountSystemTemplate',
        ),
    ]
