# Generated by Django 2.2.17 on 2021-05-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_alter_model_20210512_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsystemtemplate',
            old_name='workflow_template',
            new_name='system_template',
        ),
    ]
