# Generated by Django 2.2.17 on 2021-05-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_alter_model_20210512_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='active_workflows',
            new_name='active_templates',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='max_active_workflows',
            new_name='max_active_templates',
        ),
    ]
