# Generated by Django 2.2.17 on 2021-05-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_alter_model_20210513_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='workflow_templates',
            new_name='system_templates',
        ),
        migrations.RenameField(
            model_name='accountsystemtemplate',
            old_name='is_workflow_added',
            new_name='is_template_added',
        ),
    ]
