# Generated by Django 2.2.24 on 2021-07-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_alter_model_20210513_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.Account'),
        ),
        migrations.RunSQL("""
            UPDATE accounts_notification SET account_id = u.account_id FROM
            (SELECT id, account_id FROM accounts_user) u
            WHERE user_id = u.id;
            DELETE FROM accounts_notification WHERE account_id IS NULL;
        """)
    ]
