# Generated by Django 2.2.24 on 2021-07-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_notification_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
