# Generated by Django 2.2.24 on 2021-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_auto_20210817_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tasks_digest_subscriber',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_tasks_digest_send_time',
            field=models.DateTimeField(null=True),
        ),
    ]
