# Generated by Django 2.2.28 on 2022-07-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_user_is_onboarding_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_subscribed',
        ),
    ]
