# Generated by Django 2.2.26 on 2023-02-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_auto_20230201_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='total_users',
        ),
        migrations.RemoveField(
            model_name='userinvite',
            name='is_active',
        ),
    ]
