# Generated by Django 2.2.28 on 2023-03-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_migrate_active_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trial_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL("""
            UPDATE accounts_account
            SET trial_ended = (
                CASE
                  WHEN plan = 'free' AND plan_expiration IS NULL THEN FALSE
                  WHEN plan = 'trial' THEN FALSE
                  ELSE TRUE
                END
            )
        """)
    ]
