# Generated by Django 2.2 on 2023-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_account_tenants_active_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ai_templates_generations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='max_ai_templates_generations',
            field=models.IntegerField(default=10),
        ),
    ]
