# Generated by Django 2.2 on 2023-04-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_auto_20230405_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='max_ai_templates_generations',
            field=models.IntegerField(default=1000),
        ),
    ]
