# Generated by Django 2.2 on 2023-04-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_auto_20230410_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='max_ai_templates_generations',
            field=models.IntegerField(default=1000),
        ),
        migrations.RunSQL(
            "UPDATE accounts_account SET max_ai_templates_generations=1000"
        ),
    ]
