# Generated by Django 2.2 on 2023-04-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_auto_20230427_0549'),
    ]

    operations = [
        migrations.RunSQL(
            """ UPDATE accounts_account SET payment_card_provided=TRUE """
        ),
        migrations.RunSQL(
            """ DELETE FROM accounts_notification WHERE type = 'onboarding' """
        )
    ]
