# Generated by Django 2.2 on 2023-07-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_account_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing_plan',
            field=models.CharField(default='free', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='trial_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='trial_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.CharField(default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='trial_ended',
            field=models.BooleanField(default=False, help_text='Indicates that the trial is no longer available'),
        ),
    ]
