# Generated by Django 2.2 on 2023-07-20 08:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_auto_20230720_0820'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE accounts_account
            SET 
                billing_plan = acc.billing_plan,
                trial_end = acc.trial_end
            FROM (
                SELECT
                      id,
                  CASE
                    WHEN plan = 'trial' THEN 'premium'
                    ELSE plan
                  END AS billing_plan,
                  CASE
                    WHEN plan = 'trial' THEN plan_expiration
                    ELSE NULL
                  END AS trial_end
                FROM accounts_account
            ) acc
            WHERE acc.id = accounts_account.id
        """)
    ]
