# Generated by Django 2.2 on 2023-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_account_billing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tenant name'),
        ),
    ]
