# Generated by Django 2.2 on 2023-09-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_account_tenant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ab_id',
        ),
        migrations.RunSQL("""
            WITH accounts AS (
              SELECT aa.id
              FROM accounts_account aa 
                LEFT JOIN accounts_accountsignupdata d
                  ON d.account_id = aa.id 
              WHERE d.id IS NULL
                AND aa.is_deleted IS FALSE
            )
            INSERT INTO accounts_accountsignupdata (
              account_id,
              utm_source,
              utm_medium,
              utm_campaign,
              utm_term,
              utm_content,
              gclid
            ) SELECT
              accounts.id,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL
            FROM accounts
            ON CONFLICT (id) DO NOTHING
        """)
    ]
