# Generated by Django 2.2 on 2023-09-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_remove_account_ab_id'),
    ]

    operations = [
        migrations.RunSQL("""
            WITH accounts AS (
              SELECT id
              FROM accounts_account
              WHERE tenant_name is NULL AND lease_level = 'tenant'
            )
            UPDATE accounts_account
            SET tenant_name = 'New tenant';
        """)
    ]
