# Generated by Django 2.2 on 2023-10-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_auto_20231026_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
            preserve_default=False,
        ),
    ]
