# Generated by Django 2.2 on 2024-05-15 15:33

from django.db import migrations, models
import pneumatic_backend.accounts.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_auto_20240315_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English (USA)'), ('es', 'Spanish'), ('de', 'German'), ('fr', 'French'), ('ru', 'Russian')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=pneumatic_backend.accounts.fields.EmailLowerField(blank=True, max_length=254),
        ),
    ]
