# Generated by Django 2.2 on 2024-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0119_auto_20240605_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_fmt',
            field=models.CharField(choices=[('%B %d, %Y, %I:%M%p', 'June 12, 2024, 06:00 PM'), ('%d %B, %Y, %I:%M%p', '12 June, 2024, 06:00 PM'), ('%B %d, %Y, %H:%M', 'June 12, 2024, 18:00'), ('%d %B, %Y, %H:%M', '12 June, 2024, 18:00')], default='%B %d, %Y, %I:%M%p', max_length=20, verbose_name='Date format'),
        ),
    ]
