# Generated by Django 2.2 on 2024-07-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0121_auto_20240724_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_onboarding_finished',
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('fr', 'French'), ('ru', 'Russian')], default='en', max_length=10),
        ),
        migrations.DeleteModel(
            name='APILogs',
        ),
    ]
