# Generated by Django 2.2 on 2024-08-19 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pneumatic_backend.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_account_log_api_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.URLField(blank=True, max_length=1024, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(pneumatic_backend.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('Etc/GMT-12', '+12 Etc/GMT-12'), ('US/Samoa', '-11 US/Samoa'), ('Pacific/Honolulu', '-10 Pacific/Honolulu'), ('America/Anchorage', '-08 America/Anchorage'), ('America/Los_Angeles', '-07 America/Los_Angeles'), ('America/Denver', '-06 America/Denver'), ('America/Chicago', '-05 America/Chicago'), ('America/New_York', '-04 America/New_York'), ('America/Caracas', '-04 America/Caracas'), ('America/Buenos_Aires', '-03 America/Buenos_Aires'), ('Atlantic/South_Georgia', '-02 Atlantic/South_Georgia'), ('Atlantic/Azores', '+00 Atlantic/Azores'), ('UTC', '+00 UTC'), ('Europe/Berlin', '+02 Europe/Berlin'), ('Africa/Cairo', '+03 Africa/Cairo'), ('Europe/Moscow', '+03 Europe/Moscow'), ('Asia/Dubai', '+04 Asia/Dubai'), ('Asia/Karachi', '+05 Asia/Karachi'), ('Asia/Dhaka', '+06 Asia/Dhaka'), ('Asia/Bangkok', '+07 Asia/Bangkok'), ('Asia/Shanghai', '+08 Asia/Shanghai'), ('Asia/Tokyo', '+09 Asia/Tokyo'), ('Australia/Sydney', '+10 Australia/Sydney'), ('Pacific/Guadalcanal', '+11 Pacific/Guadalcanal'), ('Pacific/Fiji', '+12 Pacific/Fiji')], default='UTC', max_length=100),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
