# Generated by Django 2.2 on 2024-09-16 15:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0125_auto_20240903_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCheckList',
        ),
    ]
