# Generated by Django 2.2 on 2024-10-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0129_auto_20241113_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='accounts.Account'),
        ),
    ]
