# Generated by Django 2.2 on 2024-10-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0130_add_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
