export const ETableViewFieldsWidth = {
  'system-column-workflow': 376,
  'system-column-templateName': 304,
  'system-column-starter': 82,
  'system-column-progress': 80,
  'system-column-step': 304,
  'system-column-performer': 80,
  number: 80,
  text: 528,
  string: 192,
  date: 80,
  url: 304,
  checkbox: 304,
  radio: 192,
  dropdown: 192,
  file: 192,
  user: 80,
} as const;

export const EColumnWidthMinWidth = {
  'system-column-workflow': 184,
  'system-column-templateName': 80,
  'system-column-starter': 82,
  'system-column-progress': 80,
  'system-column-step': 80,
  'system-column-performer': 80,
  number: 80,
  text: 80,
  string: 80,
  date: 80,
  url: 80,
  checkbox: 80,
  radio: 80,
  dropdown: 80,
  file: 80,
  user: 80,
} as const;
