repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: powershell -Command "cd file_service; Get-ChildItem -Recurse -Include *.py | ForEach-Object { (Get-Content $_.FullName) -replace '\\s+$', '' | Set-Content $_.FullName }"
        language: system
        types: [text]
        files: ^file_service/
        require_serial: true
        pass_filenames: false

      - id: end-of-file-fixer
        name: fix end of files
        entry: powershell -Command "cd file_service; Get-ChildItem -Recurse -Include *.py | ForEach-Object { $content = Get-Content $_.FullName -Raw; if ($content -and -not $content.EndsWith([Environment]::NewLine)) { $content + [Environment]::NewLine | Set-Content $_.FullName -NoNewline } }"
        language: system
        types: [text]
        files: ^file_service/
        require_serial: true
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: powershell -Command "cd file_service; ruff check --fix --show-fixes --exit-non-zero-on-fix ."
        language: system
        types: [python]
        files: ^file_service/
        require_serial: true
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: powershell -Command "cd file_service; ruff format ."
        language: system
        types: [python]
        files: ^file_service/
        require_serial: true
        pass_filenames: false

      - id: mypy-check
        name: mypy
        entry: powershell -Command "cd file_service; mypy src/"
        language: system
        types: [python]
        files: ^file_service/src/
        require_serial: true
        pass_filenames: false