const SUB_HIDDEN_BREAKPOINT = 1440;
const DESKTOP_MIN_WIDTH_BREAKPOINT = 1000;
const MOBILE_MAX_WIDTH_BREAKPOINT = 999;

module.exports = {
  SUB_HIDDEN_BREAKPOINT,
  DESKTOP_MIN_WIDTH_BREAKPOINT,
  MOBILE_MAX_WIDTH_BREAKPOINT,
};
