# Generated by Django 2.2 on 2026-02-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0139_remove_account_external_id'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_group_permissions', to='contenttypes.ContentType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_group_permissions', to='accounts.UserGroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_group_permissions', to='auth.Permission')),
            ],
        ),
        migrations.AddIndex(
            model_name='groupobjectpermission',
            index=models.Index(fields=['group', 'permission', 'content_type', 'object_pk'], name='perm_grp_perm_ct_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='groupobjectpermission',
            index=models.Index(fields=['group', 'content_type', 'object_pk'], name='perm_grp_ct_obj_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupobjectpermission',
            unique_together={('group', 'permission', 'content_type', 'object_pk')},
        ),
    ]
