# Generated by Django 2.2 on 2024-03-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.CharField(choices=[('help-center', 'Help center')], max_length=50, unique=True),
        ),
    ]
