# Generated by Django 2.2.7 on 2019-11-07 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20191106_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='colour',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Background hex colour'),
        ),
        migrations.AddField(
            model_name='application',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Priority of app in ordering'),
        ),
    ]
