# Generated by Django 2.2.16 on 2020-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Make it active if you are sure, that the integration is ready.'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='button_text',
            field=models.CharField(help_text='Text that will be shown on the button, that redirect user to the service page.', max_length=32),
        ),
        migrations.AlterField(
            model_name='integration',
            name='long_description',
            field=models.TextField(help_text='Long description on page of the integration. You can use HTML markup here.'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(help_text='Name of service', max_length=128),
        ),
        migrations.AlterField(
            model_name='integration',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Integration order. The higher the number here the higher integration in integrations list.'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='short_description',
            field=models.CharField(help_text='Short description of service we integrated with.', max_length=300),
        ),
        migrations.AlterField(
            model_name='integration',
            name='url',
            field=models.URLField(help_text='URL to the service'),
        ),
    ]
