# Generated by Django 2.2 on 2023-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('signin', 'Sign in'), ('signup', 'Sign up'), ('reset-password', 'Reset password')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
