export enum ERoutes {
  Root = '/',
  Error = '/error/',
  Login = '/auth/signin/',
  SuperuserLogin = '/auth/superuser/',
  Register = '/auth/signup/',
  SignUpMicrosoft = '/auth/signup/microsoft/',
  SignUpGoogle = '/auth/signup/google/',
  SignUpInvite = '/auth/signup/invite/',
  CollectPaymentDetails = '/collect-payment-details',
  AfterPaymentDetailsProvided = '/after-payment-details-provided',
  Main = '/dashboard/',
  Search = '/search/',
  Settings = '/settings/',
  Profile = '/settings/profile/',
  AccountSettings = '/settings/account/',
  OAuthGoogle = '/oauth/google/',
  OAuthMicrosoft = '/oauth/microsoft/',
  OAuthSSO = '/oauth/auth0/',
  InvitesGoogle = '/oauth/invites/google/',
  Iframes = '/iframe/',
  ForgotPassword = '/auth/forgot-password/',
  ResetPassword = '/auth/reset-password/',
  ExpiredInvite = '/auth/expired-invite/',
  AccountVerificationLink = '/auth/confirm-email/',
  AccountVerification = '/auth/verification?token=:token',
  Workflows = '/workflows/',
  WorkflowDetail = '/workflows/:id/',
  TemplateView = '/templates/:id/',
  Tasks = '/tasks/',
  TaskDetail = '/tasks/:id/',
  WorkflowsInProgress = '/workflows/?type=running',
  WorkflowsCompleted = '/workflows/?type=done',
  Templates = '/templates/',
  TemplatesEdit = '/templates/edit/:id/',
  TemplatesCreate = '/templates/create/',
  TemplatesCreateAI = '/templates/create-with-ai/',
  Highlights = '/workflow-highlights/',
  HighlightsByTemplateId = '/workflow-highlights/?templates=:templateId',
  Team = '/team/',
  Reports = '/reports/',
  Help = '/help/',
  Integrations = '/integrations/',
  IntegrationsDetail = '/integrations/:id/',
  GuestTask = '/guest-task/:id/',
  Tenants = '/tenants/',
}

export enum EPublicFormRoutes {
  SharedForm = '/:id/',
  EmbeddedForm = '/embed/:id/',
  Error = '/error/',
}
