export const PNEUMATIC_SUFFIX = '| Pneumatic';

export const TITLES = {
  'Register': `Sign Up ${PNEUMATIC_SUFFIX}`,
  'RegisterInvite': `Accept Invite ${PNEUMATIC_SUFFIX}`,
  'Login': `Sign In ${PNEUMATIC_SUFFIX}`,
  'SuperuserLogin': `Superuser login ${PNEUMATIC_SUFFIX}`,
  'Main': `Dashboard ${PNEUMATIC_SUFFIX}`,
  'Error': `Oops, error ${PNEUMATIC_SUFFIX}`,
  'Users': `Team ${PNEUMATIC_SUFFIX}`,
  'Profile': `Profile ${PNEUMATIC_SUFFIX}`,
  'AccountSettings': `Account ${PNEUMATIC_SUFFIX}`,
  'Templates': `Templates ${PNEUMATIC_SUFFIX}`,
  'TemplatesEdit': `Template ${PNEUMATIC_SUFFIX}`,
  'TemplatesCreate': `Add Template ${PNEUMATIC_SUFFIX}`,
  'Workflows': `Workflows ${PNEUMATIC_SUFFIX}`,
  'Tasks': `Tasks ${PNEUMATIC_SUFFIX}`,
  'TasksDetail': `Task ${PNEUMATIC_SUFFIX}`,
  'TryForFree': 'Try for free',
  'ForgotPassword': `Forgot Password ${PNEUMATIC_SUFFIX}`,
  'ExpiredInvite': `Your Invitation Is Expired ${PNEUMATIC_SUFFIX}`,
  'ResetPassword': `Reset Password ${PNEUMATIC_SUFFIX}`,
  'Team': `Team ${PNEUMATIC_SUFFIX}`,
  'Tenants': `Tenants ${PNEUMATIC_SUFFIX}`,
  'Pricing': `Pricing ${PNEUMATIC_SUFFIX}`,
  'Checkout': `Checkout ${PNEUMATIC_SUFFIX}`,
  'WorkflowHighlights': `Workflow Highlights ${PNEUMATIC_SUFFIX}`,
  'Integrations': `Integrations ${PNEUMATIC_SUFFIX}`,
};
