# Generated by Django 2.2.14 on 2020-08-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20200730_1045'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together={('account', 'target', 'event')},
        ),
    ]
