# Generated by Django 2.2.15 on 2020-08-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20200804_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
