# Generated by Django 2.2 on 2023-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(
                help_text='Used to identify the product. Available values: "fractionalcoo", "premium"',
                max_length=100,
                null=True,
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='price',
            name='code',
            field=models.CharField(help_text='Used to identify the product price', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=False, help_text='False if price archived'),
        ),
        migrations.AlterField(
            model_name='price',
            name='max_quantity',
            field=models.PositiveIntegerField(help_text='Limit the maximum quantity to buy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(help_text='False if product archived'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_subscription',
            field=models.BooleanField(help_text='Set to true if the product is subscription'),
        ),
    ]
