# Generated by Django 2.2.5 on 2019-10-31 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_is_onboarding_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInvite'),
        ),
    ]
