# Generated by Django 2.2.5 on 2019-10-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
