# Generated by Django 2.2.7 on 2019-11-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20191108_0540'),
        ('accounts', '0014_auto_20191031_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='applications',
            field=models.ManyToManyField(to='applications.Application', verbose_name='User applications'),
        ),
    ]
