# Generated by Django 2.2.7 on 2019-11-25 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_clearbituserinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearbituserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clearbit', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
