# Generated by Django 2.2.7 on 2019-12-04 10:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20191125_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearbituserinfo',
            options={'verbose_name': 'ClearBit enrichment', 'verbose_name_plural': 'ClearBit enrichments'},
        ),
        migrations.AlterField(
            model_name='clearbituserinfo',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON'),
        ),
    ]
