# Generated by Django 2.2.10 on 2020-02-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_account_active_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_templates',
            field=models.IntegerField(default=0),
        ),
    ]
