# Generated by Django 2.2.14 on 2020-08-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_user_is_digest_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_digest_send_time',
            field=models.DateTimeField(null=True),
        ),
    ]
