# Generated by Django 2.2.16 on 2020-11-24 11:32
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_migrate_user_to_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invite',
        ),
    ]
