# Generated by Django 2.2.17 on 2020-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20201210_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
