# Generated by Django 2.2.24 on 2021-08-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_auto_20210723_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_comments_mentions_subscriber',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_new_tasks_subscriber',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_newsletters_subscriber',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_special_offers_subscriber',
            field=models.BooleanField(default=True),
        ),
    ]
