# Generated by Django 2.2.24 on 2021-08-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_auto_20210803_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('is_delivery_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('read', 'read')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='system_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.SystemMessage'),
        ),
        migrations.RunSQL(
            sql="""
              UPDATE accounts_notification an SET status = CASE 
              WHEN an.is_read IS TRUE THEN 'read' ELSE 'new' END;
            """,
            reverse_sql='',
        ),
    ]
