# Generated by Django 2.2.24 on 2021-11-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_auto_20211005_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='max_invites',
            field=models.IntegerField(default=5),
        ),
    ]
