# Generated by Django 2.2.28 on 2022-06-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_remove_account_is_subscribed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_email_unique',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='user_username_unique',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('type', 'user'), ('status', 'active')), fields=('email',), name='user_email_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('type', 'user'), ('status', 'active')), fields=('username',), name='user_username_unique'),
        ),
    ]
