# Generated by Django 2.2 on 2024-10-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0126_auto_20240916_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='payment_card_provided',
        ),
    ]
