# Generated by Django 2.2 on 2024-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0128_auto_20241101_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='active_templates',
        ),
        migrations.RemoveField(
            model_name='account',
            name='max_active_templates',
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('Etc/GMT+12', '-12 Etc/GMT+12'), ('US/Samoa', '-11 US/Samoa'), ('Pacific/Honolulu', '-10 Pacific/Honolulu'), ('America/Anchorage', '-09 America/Anchorage'), ('America/Los_Angeles', '-08 America/Los_Angeles'), ('America/Denver', '-07 America/Denver'), ('America/Chicago', '-06 America/Chicago'), ('America/New_York', '-05 America/New_York'), ('America/Caracas', '-04 America/Caracas'), ('America/Buenos_Aires', '-03 America/Buenos_Aires'), ('Atlantic/South_Georgia', '-02 Atlantic/South_Georgia'), ('Atlantic/Azores', '-01 Atlantic/Azores'), ('UTC', '+00 UTC'), ('Europe/Berlin', '+01 Europe/Berlin'), ('Africa/Cairo', '+02 Africa/Cairo'), ('Europe/Moscow', '+03 Europe/Moscow'), ('Asia/Dubai', '+04 Asia/Dubai'), ('Asia/Karachi', '+05 Asia/Karachi'), ('Asia/Dhaka', '+06 Asia/Dhaka'), ('Asia/Bangkok', '+07 Asia/Bangkok'), ('Asia/Shanghai', '+08 Asia/Shanghai'), ('Asia/Tokyo', '+09 Asia/Tokyo'), ('Australia/Sydney', '+10 Australia/Sydney'), ('Pacific/Guadalcanal', '+11 Pacific/Guadalcanal'), ('Pacific/Fiji', '+12 Pacific/Fiji')], default='UTC', max_length=100),
        ),
    ]
