# Generated by Django 2.2 on 2025-07-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0132_auto_20241109_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bucket_is_public',
            field=models.BooleanField(default=True),
        ),
    ]
