# Generated by Django 2.2 on 2025-10-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0133_account_bucket_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
