# Generated by Django 2.2 on 2025-09-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0136_auto_20251027_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='external_id',
            field=models.CharField(blank=True, help_text='External organization ID (e.g., Okta organization ID)', max_length=255, null=True),
        ),
    ]
