# Generated by Django 2.2 on 2025-11-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0137_add_external_id_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('email', 'email'), ('microsoft', 'microsoft'), ('google', 'google'), ('auth0', 'auth0'), ('okta', 'okta')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='invited_from',
            field=models.CharField(choices=[('email', 'email'), ('microsoft', 'microsoft'), ('google', 'google'), ('auth0', 'auth0'), ('okta', 'okta')], default='email', max_length=16),
        ),
    ]
