# Generated by Django 2.2 on 2025-11-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0138_auto_20251118_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='external_id',
        ),
    ]
