# Generated by Django 2.2 on 2026-03-17 03:38

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0139_remove_account_external_id'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE accounts_notification SET text = '' WHERE text IS NULL;",
            migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
