# Generated by Django 2.2 on 2026-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0144_auto_20260609_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ai_performers_enabled',
            field=models.BooleanField(default=False, help_text='Feature flag: AI agents can be assigned to and complete workflow tasks on this account'),
        ),
    ]
