# Generated by Django 2.2 on 2026-07-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0144_auto_20260609_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bucket_is_public',
        ),
    ]
