# Generated by Django 2.2 on 2026-08-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0144_auto_20260609_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='max_users',
            field=models.IntegerField(default=1000),
        ),
    ]
