# Generated by Django 5.2.17 on 2026-10-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0145_apikey_secure_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='task_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='workflow_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
