# Generated by Django 2.2 on 2026-08-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0145_apikey_secure_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='account',
            name='max_users',
            field=models.IntegerField(default=1000),
        ),
    ]
