# Generated by Django 2.2.15 on 2020-08-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_auto_20200824_1922'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE webhooks_webhook
            SET event='task_completed'
            WHERE event='task_completed_v2'
        """)
    ]
