# Generated by Django 2.2.15 on 2020-08-24 19:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_migrate_event'),
    ]

    operations = [
        migrations.RunSQL("""
        DELETE FROM webhooks_webhook
        WHERE id IN (
        SELECT id
          FROM webhooks_webhook w INNER JOIN (
            SELECT account_id
            FROM webhooks_webhook w
            WHERE is_deleted IS FALSE
              AND event in ('task_completed', 'task_completed_v2')
            GROUP BY account_id
            HAVING count(id) = 2
          ) w2 ON (w.account_id = w2.account_id AND w.event = 'task_completed') 
        )
        """),
        migrations.RunSQL("""
            UPDATE webhooks_webhook
            SET event='task_completed'
            WHERE event='task_completed_v2'
        """)
    ]
