# Generated by Django 2.2.7 on 2019-12-05 11:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_auto_20191204_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('run_allowed', models.ManyToManyField(related_name='run_allowed', to=settings.AUTH_USER_MODEL, verbose_name='Allowed to run')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('step_id', models.PositiveIntegerField()),
                ('Process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.Process')),
            ],
        ),
        migrations.CreateModel(
            name='StepDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('process_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.ProcessDef')),
                ('responsible', models.ManyToManyField(related_name='responsible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepFieldDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'String'), (1, 'Text'), (2, 'Number'), (3, 'File')])),
                ('name', models.CharField(max_length=64)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.StepDef')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field_id', models.PositiveIntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.Step')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('process_def', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='processes.ProcessDef')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='processes.Snapshot'),
        ),
        migrations.CreateModel(
            name='KickoffFieldDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'String'), (1, 'Text'), (2, 'Number'), (3, 'File')])),
                ('name', models.CharField(blank=True, max_length=64)),
                ('process_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kickoff', to='processes.ProcessDef')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KickoffField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.PositiveIntegerField()),
                ('value', models.TextField(blank=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kickoff', to='processes.Process')),
            ],
        ),
    ]
