# Generated by Django 2.2.7 on 2019-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepdef',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
