# Generated by Django 2.2.7 on 2019-12-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_stepdef_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, 'process in work'), (1, 'process ended')], default=0),
        ),
    ]
