# Generated by Django 2.2.7 on 2020-01-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='processes.Process'),
        ),
    ]
