# Generated by Django 2.2.11 on 2020-03-23 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0011_auto_20200311_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KickoffFieldDef',
            new_name='KickoffFieldTemplate',
        ),
        migrations.RenameField(
            model_name='kickofffieldtemplate',
            old_name='process_def',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='current_step',
            new_name='current_task',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='steps_count',
            new_name='tasks_count',
        ),
        migrations.AlterField(
            model_name='stepfield',
            name='step',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fields',
                to='processes.Step'
            ),
        ),
        migrations.AlterField(
            model_name='stepfielddef',
            name='step',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fields',
                to='processes.StepDef'
            ),
        ),
        migrations.AlterField(
            model_name='Step',
            name='process',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to='processes.Process'
            ),
        ),
        migrations.RenameField(
            model_name='stepdef',
            old_name='process_def',
            new_name='template'
        ),
        migrations.RenameModel(
            old_name='StepFieldDef',
            new_name='TaskFieldTemplate',
        ),
        migrations.RenameModel(
            old_name='Step',
            new_name='Task'
        ),
        migrations.RenameModel(
            old_name='StepDef',
            new_name='TaskTemplate'
        ),
    ]
