# Generated by Django 2.2.11 on 2020-03-23 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0029_userinvite_invited_by'),
        ('processes', '0012_auto_20200323_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessDef',
            new_name='Template',
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='processes.Process'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='responsible',
            field=models.ManyToManyField(related_name='tasktemplate_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.Template'),
        ),
    ]
