# Generated by Django 2.2.11 on 2020-03-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0013_auto_20200323_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='process_def',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='stepfield',
            old_name='step',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='taskfieldtemplate',
            old_name='step',
            new_name='task',
        ),
    ]
