# Generated by Django 2.2.11 on 2020-03-23 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0014_auto_20200323_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepField',
            new_name='TaskField',
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ManyToManyField(related_name='task_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='processes.Template'),
        ),
    ]
