# Generated by Django 2.2.11 on 2020-04-06 07:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0029_userinvite_invited_by'),
        ('processes', '0015_auto_20200323_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='Workflow',
        ),
    ]
