# Generated by Django 2.2.11 on 2020-04-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0016_auto_20200406_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kickofffieldtemplate',
            old_name='template',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='template',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='tasktemplate',
            old_name='template',
            new_name='workflow',
        ),
    ]
