# Generated by Django 2.2.11 on 2020-04-06 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0017_auto_20200406_0727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTemplate',
            new_name='TaskWorkflow',
        ),
    ]
