# Generated by Django 2.2.12 on 2020-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0018_auto_20200406_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='finalizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='finalizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default comment'), (1, 'Return task'), (2, 'Process finished')], default=0),
        ),
    ]
