# Generated by Django 2.2.12 on 2020-04-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0019_auto_20200423_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
