# Generated by Django 2.2.12 on 2020-05-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_userinvite_invited_from'),
        ('processes', '0021_auto_20200429_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickofffieldtemplate',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kickofffieldtemplate',
            name='api_name',
            field=models.TextField(blank=True),
        ),
    ]
