# Generated by Django 2.2.12 on 2020-04-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0021_auto_20200424_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='responsible',
        ),
    ]
