# Generated by Django 2.2.12 on 2020-04-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0019_auto_20200423_0934'),
        ('processes', '0025_auto_20200427_1923'),
    ]

    operations = [
    ]
