# Generated by Django 2.2.12 on 2020-05-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0026_auto_20200507_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickoff',
            name='workflow',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kickoff', to='processes.Workflow'),
        ),
    ]
