# Generated by Django 2.2.12 on 2020-05-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0020_auto_20200427_2142'),
        ('processes', '0026_merge_20200428_0859'),
    ]

    operations = [
    ]
