# Generated by Django 2.2.12 on 2020-05-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0027_auto_20200508_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickofffieldtemplate',
            name='api_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
