# Generated by Django 2.2.13 on 2020-06-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0032_workflow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
