# Generated by Django 2.2.13 on 2020-06-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0034_auto_20200623_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KickoffFieldTemplate',
            new_name='FieldTemplate',
        ),
    ]
