# Generated by Django 2.2.13 on 2020-06-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0035_auto_20200629_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtemplate',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.TaskWorkflow'),
        ),
        migrations.DeleteModel(
            name='TaskFieldTemplate',
        ),
    ]
