# Generated by Django 2.2.13 on 2020-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0037_auto_20200629_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
