# Generated by Django 2.2.13 on 2020-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0037_auto_20200629_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_legacy_workflow',
            field=models.BooleanField(default=False, help_text='Workflow is deleted'),
        ),
        migrations.AddField(
            model_name='process',
            name='legacy_workflow_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
