# Generated by Django 2.2.13 on 2020-07-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0039_auto_20200701_1121'),
        ('processes', '0038_auto_20200701_0431'),
    ]

    operations = [
    ]
