# Generated by Django 2.2.13 on 2020-07-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0038_auto_20200630_1300'),
        ('processes', '0040_merge_20200701_1352'),
    ]

    operations = [
    ]
