# Generated by Django 2.2.13 on 2020-07-10 07:56

from django.db import migrations, models
import django.db.models.deletion
from pneumatic_backend.generics.mixins.models import SoftDeleteMixin


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0043_drop_aborted_processes_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworkflow',
            name='delay',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, 'Process in work'), (1, 'Process done'), (2, 'Process aborted'), (3, 'Process delayed')], default=0),
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('duration', models.DurationField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_end_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Task')),
            ],
            options={
                'abstract': False,
            },
            bases=(SoftDeleteMixin, models.Model),
        ),
    ]
