# Generated by Django 2.2.14 on 2020-07-15 12:55

from django.db import migrations, models
import django.db.models.deletion
from pneumatic_backend.generics.mixins.models import SoftDeleteMixin


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20200624_1054'),
        ('processes', '0045_fieldselection_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfield',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output', to='processes.Task'),
        ),
        migrations.CreateModel(
            name='KickoffValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kickoff', to='processes.Process')),
            ],
            options={
                'abstract': False,
            },
            bases=(SoftDeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='taskfield',
            name='kickoff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output', to='processes.KickoffValue'),
        ),
    ]
