# Generated by Django 2.2.14 on 2020-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0047_workflowtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='tasks_count',
            field=models.IntegerField(default=0),
        ),
    ]
