# Generated by Django 2.2.14 on 2020-07-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0048_auto_20200723_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplate',
            name='description',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='order',
            field=models.IntegerField(default=0, help_text='The list will be ordered from bigger to the smaller'),
        ),
    ]
