# Generated by Django 2.2.14 on 2020-07-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0049_auto_20200724_0851'),
        ('processes', '0049_auto_20200724_1011'),
    ]

    operations = [
    ]
