# Generated by Django 2.2.14 on 2020-08-11 10:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from pneumatic_backend.generics.mixins.models import SoftDeleteMixin


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0051_delete_aborted_processes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('draft', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='processes.Workflow')),
            ],
            options={
                'abstract': False,
            },
            bases=(SoftDeleteMixin, models.Model),
        ),
    ]
