# Generated by Django 2.2.14 on 2020-08-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0053_fill_status_updated_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status_updated',
            field=models.DateTimeField(),
        ),
    ]
