# Generated by Django 2.2.14 on 2020-08-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0054_auto_20200810_1236'),
        ('processes', '0052_workflowdraft'),
    ]

    operations = [
    ]
