# Generated by Django 2.2.15 on 2020-08-14 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0054_auto_20200810_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='colour',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Background hex colour'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='URL to image for this app'),
        ),
    ]
