# Generated by Django 2.2.14 on 2020-08-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0055_merge_20200813_0931'),
        ('processes', '0055_auto_20200817_0947'),
    ]

    operations = [
    ]
