# Generated by Django 2.2.15 on 2020-08-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0055_auto_20200814_1010'),
        ('processes', '0056_migrate_generic_workflow'),
    ]

    operations = [
    ]
