# Generated by Django 2.2.15 on 2020-08-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0058_restore_aborted_processes'),
        ('processes', '0057_merge_20200821_1008'),
    ]

    operations = [
    ]
