# Generated by Django 2.2.15 on 2020-09-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0058_restore_aborted_processes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtemplate',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='taskfield',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='fieldtemplate',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown')], max_length=10),
        ),
    ]
