# Generated by Django 2.2.16 on 2020-09-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0059_merge_20200827_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='image',
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown')], max_length=10),
        ),
    ]
