# Generated by Django 2.2.16 on 2020-09-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0060_auto_20200903_1036'),
        ('processes', '0059_auto_20200901_1026'),
    ]

    operations = [
    ]
