# Generated by Django 2.2.15 on 2020-09-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0061_merge_20200903_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskresponsible',
            name='is_deleted',
        ),
    ]
