# Generated by Django 2.2.16 on 2020-09-11 09:26

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0061_merge_20200903_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='search_content',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='search_content',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='search_content',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='search_content',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
