# Generated by Django 2.2.16 on 2020-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0062_remove_taskresponsible_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfield',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
