# Generated by Django 2.2.16 on 2020-09-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0062_auto_20200911_0926'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER process_ins BEFORE INSERT OR UPDATE ON processes_process FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(search_content, 'pg_catalog.english', name);
            ''',
            reverse_sql='''
            DROP TRIGGER IF EXISTS process_ins ON processes_process;
            '''
        ),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER tasks_ins BEFORE INSERT OR UPDATE ON processes_task FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(search_content, 'pg_catalog.english', name, description);
            ''',
            reverse_sql='''
            DROP TRIGGER IF EXISTS tasks_ins ON processes_task;
            '''
        ),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER comments_ins BEFORE INSERT OR UPDATE ON processes_comment FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(search_content, 'pg_catalog.english', text);
            ''',
            reverse_sql='''
            DROP TRIGGER IF EXISTS comments_ins ON processes_comment;
            '''
        ),
        migrations.RunSQL(
            sql='''
            CREATE INDEX process_idx ON processes_process USING gin(search_content) WHERE is_deleted is FALSE;
            ''',
            reverse_sql='''
            DROP INDEX IF EXISTS process_idx;
            '''
        ),
        migrations.RunSQL(
            sql='''
            CREATE INDEX task_idx ON processes_task USING gin(search_content) WHERE is_deleted is FALSE;
            ''',
            reverse_sql='''
            DROP INDEX IF EXISTS task_idx;
            '''
        ),
        migrations.RunSQL(
            sql='''
            CREATE INDEX comment_idx ON processes_comment USING gin(search_content) WHERE is_deleted is FALSE;
            ''',
            reverse_sql='''
            DROP INDEX IF EXISTS comment_idx;
            '''
        )
    ]
