# Generated by Django 2.2.16 on 2020-09-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0063_auto_20200911_0926'),
        ('processes', '0064_auto_20200915_0615'),
    ]

    operations = [
    ]
