# Generated by Django 2.2.16 on 2020-09-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0064_auto_20200915_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickoff',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kickoff', to='processes.Workflow'),
        ),
        migrations.AlterField(
            model_name='taskworkflowoutput',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output', to='processes.TaskWorkflow'),
        ),
        migrations.AddConstraint(
            model_name='kickoff',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('workflow',), name='kickoff_workflow_unique'),
        ),
        migrations.AddConstraint(
            model_name='taskworkflowoutput',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('task',), name='task_workflow_output_task_unique'),
        ),
    ]
