# Generated by Django 2.2.16 on 2020-09-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0064_auto_20200915_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
