# Generated by Django 2.2.16 on 2020-09-16 09:41

from django.db import migrations


def fill_search_content(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0065_merge_20200915_0940'),
    ]

    operations = [
        migrations.RunPython(fill_search_content, reverse_code=migrations.RunPython.noop),
    ]
