# Generated by Django 2.2.16 on 2020-09-17 13:08

from django.db import migrations


def fill_search_content(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0066_auto_20200916_0941'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER workflow_ins BEFORE INSERT OR UPDATE ON processes_workflow FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(search_content, 'pg_catalog.english', name);
            ''',
            reverse_sql='''
            DROP TRIGGER IF EXISTS workflow_ins ON processes_workflow;
            '''
        ),
        migrations.RunSQL(
            sql='''
            CREATE INDEX workflow_idx ON processes_workflow USING gin(search_content) WHERE is_deleted is FALSE;
            ''',
            reverse_sql='''
            DROP INDEX IF EXISTS workflow_idx;
            '''
        ),
        migrations.RunPython(fill_search_content, reverse_code=migrations.RunPython.noop),
    ]
