# Generated by Django 2.2.16 on 2020-09-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0065_auto_20200917_0954'),
        ('processes', '0067_auto_20200917_1308'),
    ]

    operations = [
    ]
