# Generated by Django 2.2.16 on 2020-09-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0069_merge_20200918_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
