# Generated by Django 2.2.16 on 2020-09-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0069_auto_20200921_1136'),
        ('processes', '0070_process_version'),
    ]

    operations = [
    ]
