# Generated by Django 2.2.16 on 2020-09-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0071_merge_20200921_1216'),
        ('processes', '0065_auto_20200922_1241'),
    ]

    operations = [
    ]
