# Generated by Django 2.2.16 on 2020-09-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0072_merge_20200923_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url_template',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='taskworkflow',
            name='url_template',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
