# Generated by Django 2.2.16 on 2020-09-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0073_auto_20200924_1447'),
        ('processes', '0073_auto_20200925_1208'),
    ]

    operations = [
    ]
