# Generated by Django 2.2.16 on 2020-10-05 12:31

from django.db import migrations


def add_processes_to_attach(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0077_fileattachment_process'),
    ]

    operations = [
        migrations.RunPython(add_processes_to_attach, reverse_code=migrations.RunPython.noop)
    ]
