# Generated by Django 2.2.16 on 2020-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0080_auto_20201013_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='type',
            field=models.CharField(choices=[('generic', 'Generic workflows'), ('owner_onboarding', 'Workflow to onboard account owners')], default='generic', max_length=16),
        ),
    ]
