# Generated by Django 2.2.16 on 2020-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0084_auto_20201026_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='type',
            field=models.CharField(choices=[('custom', 'custom'), ('generic', 'generic'), ('generic_clone', 'generic clone'), ('invited_onboarding', 'onboarding invited')], default='custom', max_length=24),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='type',
            field=models.CharField(choices=[('generic', 'Generic workflows'), ('owner_onboarding', 'Account owners onboarding workflow'), ('invited_onboarding', 'Invited users onboarding workflow')], default='generic', max_length=24),
        ),
    ]
