# Generated by Django 2.2.16 on 2020-11-02 13:22

from django.db import migrations


def workflows_from_onboarding_to_admin(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0089_auto_20201102_1322'),
    ]

    operations = [
        migrations.RunPython(workflows_from_onboarding_to_admin, reverse_code=migrations.RunPython.noop)
    ]
