# Generated by Django 2.2.16 on 2020-11-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0093_auto_20201113_1119'),
        ('processes', '0093_auto_20201111_0906'),
    ]

    operations = [
    ]
