# Generated by Django 2.2.16 on 2020-11-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0095_merge_20201117_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworkflow',
            name='is_starter_responsible',
            field=models.BooleanField(default=False),
        ),
    ]
