# Generated by Django 2.2.16 on 2020-11-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20201124_1132'),
        ('processes', '0095_merge_20201117_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='taskworkflow',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
