# Generated by Django 2.2.16 on 2020-11-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0097_auto_20201125_1129'),
        ('processes', '0097_set_account_for_tasks'),
    ]

    operations = [
    ]
