# Generated by Django 2.2.16 on 2020-11-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0097_process_process_starter'),
        ('processes', '0097_auto_20201125_1129'),
    ]

    operations = [
    ]
