# Generated by Django 2.2.17 on 2020-12-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0098_merge_20201130_0656'),
        ('processes', '0098_merge_20201127_1132'),
    ]

    operations = [
    ]
