# Generated by Django 2.2.17 on 2021-01-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0103_fieldtemplate_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='output_responsible',
            field=models.ManyToManyField(related_name='task_responsible', to='processes.TaskField'),
        ),
        migrations.AddField(
            model_name='taskworkflow',
            name='output_responsible',
            field=models.ManyToManyField(related_name='tasktemplate_output_responsible', to='processes.FieldTemplate'),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown'), ('file', 'File'), ('user', 'User')], max_length=10),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown'), ('file', 'File'), ('user', 'User')], max_length=10),
        ),
    ]
