# Generated by Django 2.2.17 on 2021-03-03 11:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from pneumatic_backend.generics.mixins.models import SoftDeleteMixin


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0104_auto_20210131_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0)),
                ('template_id', models.PositiveIntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=(SoftDeleteMixin, models.Model),
        ),
    ]
