# Generated by Django 2.2.17 on 2021-03-12 12:05

from django.db import migrations


def fill_template_id(apps, schema_editor):
    pass


def reverse_code(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0107_auto_20210312_1205'),
    ]

    operations = [
        migrations.RunPython(code=fill_template_id, reverse_code=reverse_code)
    ]
