# Generated by Django 2.2.17 on 2021-03-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0107_template_to_template_id'),
        ('processes', '0105_auto_20210312_0939'),
    ]

    operations = [
    ]
