# Generated by Django 2.2.17 on 2021-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0113_join_fields_with_tasks_directly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='fieldtemplate',
            name='task_output',
        ),
        migrations.AlterField(
            model_name='predicate',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equal'), ('not_equals', 'Not equal'), ('exists', 'Exists'), ('not_exists', 'Not exists'), ('contains', 'Contains'), ('not_contains', 'Not contains'), ('more_than', 'More than'), ('less_than', 'Less than')], max_length=30),
        ),
        migrations.AlterField(
            model_name='predicatetemplate',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equal'), ('not_equals', 'Not equal'), ('exists', 'Exists'), ('not_exists', 'Not exists'), ('contains', 'Contains'), ('not_contains', 'Not contains'), ('more_than', 'More than'), ('less_than', 'Less than')], max_length=30),
        ),
        migrations.DeleteModel(
            name='TaskWorkflowOutput',
        ),
    ]
