# Generated by Django 2.2.17 on 2021-04-07 12:02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0114_auto_20210407_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_first_started',
            field=models.DateTimeField(help_text='set when the task becomes active for the first time', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_in',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='taskworkflow',
            name='due_in',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_started',
            field=models.DateTimeField(help_text='set every time the task becomes active', null=True),
        )
    ]
