# Generated by Django 2.2.17 on 2021-04-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0116_due_in_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworkflow',
            name='api_name',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
