# Generated by Django 2.2.17 on 2021-04-16 10:02

from django.db import migrations, models
from pneumatic_backend.generics.mixins.models import SoftDeleteMixin


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0118_set_date_first_started_for_broken_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskForList',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=280)),
                ('workflow_name', models.CharField(max_length=120)),
                ('estimated_end_date', models.DateTimeField(null=True)),
            ],
            options={
                'managed': False,
            },
            bases=(SoftDeleteMixin, models.Model),
        ),
    ]
