# Generated by Django 2.2.17 on 2021-05-07 09:14

from django.db import migrations


def backwards(*args, **kwards):
    pass


def forwards(*args, **kwards):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0123_auto_20210430_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='url_template',
        ),
        migrations.RemoveField(
            model_name='taskworkflow',
            name='url',
        ),
        migrations.RemoveField(
            model_name='taskworkflow',
            name='url_template',
        ),
        migrations.RunPython(
            code=forwards,
            reverse_code=backwards,
            atomic=True
        )
    ]
