# Generated by Django 2.2.17 on 2021-05-12 07:33
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_alter_model_20210512_0652'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0128_auto_20210512_0700'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TRIGGER IF EXISTS workflow_ins ON processes_template',
            reverse_sql='''
                CREATE TRIGGER workflow_ins BEFORE INSERT OR UPDATE 
                    ON processes_template FOR EACH ROW EXECUTE PROCEDURE 
                    tsvector_update_trigger(
                        search_content, 
                        'pg_catalog.english', 
                        name
                    )
            '''
        ),
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS workflow_idx',
            reverse_sql='''
                CREATE INDEX workflow_idx 
                    ON processes_template USING gin(search_content)
                WHERE is_deleted is FALSE;
            '''
        ),
        migrations.RenameModel(
            old_name='Workflow',
            new_name='Template',
        ),
        migrations.RunSQL(
            sql='''
             CREATE TRIGGER templates_ins BEFORE INSERT OR UPDATE 
                 ON processes_template FOR EACH ROW EXECUTE PROCEDURE 
                 tsvector_update_trigger(
                     search_content, 
                     'pg_catalog.english', 
                     name
                 )
            ''',
            reverse_sql='''
             DROP TRIGGER IF EXISTS templates_ins ON processes_template;
         '''
        ),
        migrations.RunSQL(
            sql='''
             CREATE INDEX templates_idx ON processes_template 
                 USING gin(search_content) 
             WHERE is_deleted is FALSE
            ''',
            reverse_sql='''DROP INDEX IF EXISTS templates_idx'''
        ),
    ]
