# Generated by Django 2.2.17 on 2021-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0129_auto_20210512_0733'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kickoff',
            name='kickoff_workflow_unique',
        ),
        migrations.RemoveConstraint(
            model_name='tasktemplate',
            name='processes_tasktemplate_workflow_api_name_unique',
        ),
        migrations.RenameField(
            model_name='kickoff',
            old_name='workflow',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='workflow',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='tasktemplate',
            old_name='workflow',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='templatedraft',
            old_name='workflow',
            new_name='template',
        ),
        migrations.AlterField(
            model_name='process',
            name='is_legacy_workflow',
            field=models.BooleanField(default=False, help_text='Template is deleted'),
        ),
        migrations.AddConstraint(
            model_name='kickoff',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('template',), name='kickoff_template_unique'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('template', 'api_name'), name='processes_tasktemplate_template_api_name_unique'),
        ),
    ]
