# Generated by Django 2.2.24 on 2021-07-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0137_auto_20210621_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='public_success_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
