# Generated by Django 2.2.24 on 2021-06-22 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0138_auto_20210621_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='process_starter',
            new_name='workflow_starter',
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default comment'), (1, 'Return task'), (2, 'Workflow finished')], default=0),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.IntegerField(choices=[(0, 'Workflow in work'), (1, 'Workflow done'), (2, 'Workflow aborted'), (3, 'Workflow delayed')], default=0),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='processes.Template'),
        ),
        migrations.AddConstraint(
            model_name='kickoffvalue',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('workflow',), name='kickoff_value_workflow_unique'),
        ),
    ]
