# Generated by Django 2.2.24 on 2021-08-02 11:39

from django.conf import settings
from django.db import migrations, models


def forward(apps, schema_editor):
    pass

def backward(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0140_auto_20210622_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='performers',
            field=models.ManyToManyField(related_name='performers', to=settings.AUTH_USER_MODEL, verbose_name='All performers for all tasks in the template'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='action',
            field=models.CharField(choices=[('skip_task', 'Skip task'), ('start_task', 'Start task'), ('end_process', 'End workflow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conditiontemplate',
            name='action',
            field=models.CharField(choices=[('skip_task', 'Skip task'), ('start_task', 'Start task'), ('end_process', 'End workflow')], max_length=20),
        ),
        migrations.RunPython(code=forward, reverse_code=backward),
    ]
