# Generated by Django 2.2.24 on 2021-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0146_create_raw_performers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='output_responsible',
        ),
        migrations.RemoveField(
            model_name='task',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='is_starter_responsible',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='output_responsible',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='responsible',
        ),
        migrations.AlterField(
            model_name='rawperformer',
            name='api_name',
            field=models.CharField(blank=True, help_text='For quick access to the api_name field ', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='rawperformer',
            name='task_performer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawperformertemplate',
            name='api_name',
            field=models.CharField(blank=True, help_text='For quick access to the api_name field ', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='performers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TaskResponsible',
        ),
    ]
