# Generated by Django 2.2.24 on 2021-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0147_auto_20211001_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='task',
            name='is_skipped',
            field=models.BooleanField(default=False),
        )
    ]
