# Generated by Django 2.2.24 on 2022-02-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0150_taskperformer_directly_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='tasks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop
        )
    ]
