# Generated by Django 2.2.27 on 2022-04-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0152_auto_20220411_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfield',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.Workflow'),
        ),
        migrations.RunSQL("""
        UPDATE processes_taskfield AS ptf SET workflow_id = CASE
            WHEN ptf.kickoff_id IS NOT NULL THEN (
                SELECT workflow_id
                FROM processes_kickoffvalue
                WHERE id = ptf.kickoff_id
            )
            WHEN ptf.task_id IS NOT NULL THEN (
                SELECT workflow_id
                FROM processes_task
                WHERE id = ptf.task_id
            )
            END
        """)
    ]
