# Generated by Django 2.2.27 on 2022-04-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0154_auto_20220415_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfield',
            options={'ordering': ['-order', '-id']},
        ),
    ]
