# Generated by Django 2.2.27 on 2022-04-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0156_auto_20220419_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfield',
            options={'ordering': ['-order', 'id']},
        ),
    ]
