# Generated by Django 2.2.28 on 2022-08-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0159_auto_20220709_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskperformer',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL("""
            WITH tasks AS (
              SELECT id, date_completed
              FROM processes_task
              WHERE is_completed IS TRUE
              AND is_deleted IS FALSE
            )
            UPDATE processes_taskperformer ptp 
              SET date_completed = tasks.date_completed
            FROM tasks
            WHERE tasks.id = ptp.task_id
              AND ptp.directly_status != 1
              AND ptp.is_completed IS TRUE
        """)
    ]
