# Generated by Django 2.2.28 on 2022-06-21 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0161_auto_20220621_1558'),
    ]

    operations = [
        migrations.RunSQL(
            """ WITH with_t_owners_data AS (
                  SELECT
                    id, 
                    jsonb_build_object('template_owners', data->'run_allowed') AS data
                  FROM processes_templateversion
                  WHERE 
                    data->'run_allowed' IS NOT NULL
                    AND is_deleted IS FALSE
                    AND (
                      data->'template_owners' IS NULL
                      OR jsonb_array_length(data->'template_owners') = 0
                    )
                )
                UPDATE processes_templateversion ptv SET data = ptv.data || with_t_owners_data.data
                FROM with_t_owners_data
                WHERE ptv.id = with_t_owners_data.id """
        )
    ]
