# Generated by Django 2.2.26 on 2022-09-14 09:19

from django.db import migrations, models
import django.db.models.deletion
import pneumatic_backend.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_auto_20220602_0552'),
        ('processes', '0162_migrate_template_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateIntegrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('api', models.BooleanField(default=False)),
                ('zapier', models.BooleanField(default=False)),
                ('webhooks', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='processes.Template')),
            ],
            options={
                'abstract': False,
            },
            bases=(pneumatic_backend.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
    ]
