# Generated by Django 2.2.28 on 2022-10-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0166_auto_20220920_1702'),
    ]

    operations = [
        migrations.RunSQL("""
            -- set account id for all template tasks
            
            WITH ptt_without_account_id AS (
              SELECT
                tt.id AS task_id,
                t.account_id AS account_id
              FROM processes_template t
              INNER JOIN processes_tasktemplate tt 
                ON tt.template_id = t.id 
                AND tt.account_id IS NULL 
            )
            UPDATE processes_tasktemplate ptt 
              SET account_id=ptt_without_account_id.account_id
            FROM ptt_without_account_id
            WHERE ptt.id = ptt_without_account_id.task_id
        """),
        migrations.RunSQL("""
            -- set account id for all tasks
    
            WITH pt_without_account_id AS (
              SELECT
                pt.id AS task_id,
                pw.account_id AS account_id
              FROM processes_task pt
                INNER JOIN processes_workflow pw
                  on pt.workflow_id = pw.id
              WHERE pt.account_id IS NULL 
            )
            UPDATE processes_task pt 
              SET account_id=pt_without_account_id.account_id
            FROM pt_without_account_id
            WHERE pt.id = pt_without_account_id.task_id
        """),
        migrations.RunSQL("""
            -- set api name for broken template fields selections
            
            UPDATE processes_fieldtemplateselection 
              SET api_name = 'selection-'||md5(random()::text) 
            WHERE api_name IS NULL
        """),
        migrations.RunSQL("""
            -- set api name for broken workflow fields selections
            -- where selection template exists
            
            WITH selections_without_api_name AS (
               SELECT s.id, ts.api_name
               FROM processes_fieldselection s
                 INNER JOIN processes_fieldtemplateselection ts
                   ON s.template_id = ts.id
               WHERE
                s.api_name IS NULL
                AND s.template_id is NOT NULL
            )
            UPDATE processes_fieldselection SET api_name = s.api_name
            FROM selections_without_api_name s
            WHERE s.id = processes_fieldselection.id
        """),
        migrations.RunSQL("""
            -- set api name for broken workflow fields selections
            -- where selection template not exists and api-name not exists 
            
            WITH selections_without_api_name AS (
               SELECT s.id
               FROM processes_fieldselection s
               WHERE
                s.api_name IS NULL
                AND s.template_id is NULL
            )
            UPDATE processes_fieldselection SET api_name = 'selection-'||md5(random()::text) 
            FROM selections_without_api_name s
            WHERE s.id = processes_fieldselection.id
        """),
        migrations.RunSQL("""
            -- set api name for broken workflow fields selections
            -- where selection template not found and api-name not exists 
    
            WITH selections_without_api_name AS (
               SELECT s.id
               FROM processes_fieldselection s
                 LEFT JOIN processes_fieldtemplateselection ts
                   ON s.template_id = ts.id
               WHERE
                s.api_name IS NULL
                AND s.template_id IS NOT NULL
                AND ts.id IS NULL
            )
            UPDATE processes_fieldselection SET api_name = 'selection-'||md5(random()::text) 
            FROM selections_without_api_name s
            WHERE s.id = processes_fieldselection.id
        """),
    ]
