# Generated by Django 2.2.28 on 2022-10-18 22:00
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0167_auto_20221018_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickoffvalue',
            name='workflow',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='kickoff', to='processes.Workflow'),
        ),
        migrations.AlterField(
            model_name='task',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='accounts.Account', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='accounts.Account', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='template_owners',
            field=models.ManyToManyField(
                related_name='template_owners',
                to=settings.AUTH_USER_MODEL,
                verbose_name='template owners'
            ),
        ),
        migrations.AddField(
            model_name='taskperformer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fieldselection',
            name='api_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='api_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fieldtemplateselection',
            name='api_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='api_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='api_name',
            field=models.CharField(max_length=200),
        ),
    ]
