# Generated by Django 2.2.28 on 2022-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0169_auto_20221019_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistselection',
            name='value_template',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.RunSQL("""
            UPDATE processes_checklistselection SET value_template=value
        """),
        migrations.AddField(
            model_name='task',
            name='checklists_marked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='checklists_total',
            field=models.IntegerField(default=0),
        ),
    ]
