# Generated by Django 2.2.28 on 2022-12-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0172_auto_20221201_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay',
            name='directly_status',
            field=models.IntegerField(choices=[(0, 'no status'), (1, 'deleted'), (2, 'created')], default=0),
        ),
    ]
