# Generated by Django 2.2.26 on 2023-03-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0178_taskfield_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
