# Generated by Django 2.2.28 on 2023-03-17 15:26

from django.db import migrations, models
import django.db.models.deletion
import pneumatic_backend.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0180_auto_20230316_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='RawDueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('rule', models.CharField(choices=[('before field', 'before field'), ('after field', 'after field'), ('after workflow started', 'after workflow started'), ('after task started', 'after task started'), ('after task completed', 'after task completed')], max_length=100)),
                ('source_id', models.CharField(max_length=200, null=True)),
                ('template_id', models.IntegerField(null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_due_date', to='processes.Task')),

            ],
            options={
                'ordering': ('pk',),
            },
            bases=(pneumatic_backend.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
    ]
