# Generated by Django 2.2.26 on 2023-03-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0181_auto_20230317_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='api_name',
            field=models.CharField(max_length=200, default='default'),
            preserve_default=False,
        ),
        migrations.RunSQL("""
            UPDATE processes_task SET api_name=tt.api_name
            FROM (
                SELECT ptt.id, ptt.api_name
                FROM processes_task pt
                   INNER JOIN processes_tasktemplate ptt
                     ON pt.template_id=ptt.id
            ) tt
            WHERE template_id=tt.id
        """)
    ]
