# Generated by Django 2.2 on 2023-08-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0189_auto_20230726_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtemplatecategory',
            name='template_color',
            field=models.CharField(help_text='templates color (hex)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='systemtemplatecategory',
            name='color',
            field=models.CharField(help_text='category color (hex)', max_length=20, null=True),
        ),
    ]
