# Generated by Django 2.2 on 2023-08-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0190_auto_20230802_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemtemplate',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='systemtemplate',
            name='order',
        ),
    ]
