# Generated by Django 2.2 on 2023-12-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0194_migrate_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowevent',
            name='task',
            field=models.ForeignKey(
                help_text='Not null for task events and comments',
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='events',
                to='processes.Task'
            ),
        ),
        migrations.RunSQL("""
        UPDATE processes_workflowevent SET task_id = task_event.task_id 
        FROM (
            SELECT	
            id,	
            (task_json->'id')::int AS task_id
            FROM processes_workflowevent
            WHERE is_deleted IS FALSE
               AND type IN (2, 3, 4, 5, 8, 9, 13, 14, 15, 18)
        ) task_event
        WHERE processes_workflowevent.id = task_event.id
        """)
    ]
