# Generated by Django 2.2 on 2023-12-28 20:18

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0197_fileattachment_search_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfield',
            name='search_content',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        )
    ]
