# Generated by Django 2.2 on 2024-02-06 17:47

from django.db import migrations, models
import django.contrib.postgres.search


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0200_workflowevent_clear_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='clear_description',
            field=models.TextField(blank=True, help_text='Does not contains markdown', null=True),
        ),
        migrations.AddField(
            model_name='taskfield',
            name='clear_value',
            field=models.TextField(blank=True, help_text='Does not contains markdown', null=True),
        ),
        migrations.AddField(
            model_name='kickoffvalue',
            name='clear_description',
            field=models.TextField(
                blank=True,
                help_text='Does not contains markdown',
                null=True
           ),
        ),
        migrations.AddField(
            model_name='kickoffvalue',
            name='search_content',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
