# Generated by Django 2.2 on 2024-03-06 07:31

from django.db import migrations, models
import pneumatic_backend.processes.models.templates.template


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0204_auto_20240306_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='embed_id',
            field=models.CharField(default=pneumatic_backend.processes.models.templates.template.get_new_embed_id, max_length=32),
        ),
        migrations.AlterField(
            model_name='template',
            name='public_id',
            field=models.CharField(default=pneumatic_backend.processes.models.templates.template.get_new_public_id, max_length=32),
        ),
    ]
