# Generated by Django 2.2 on 2024-06-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0206_set_workflow_events_tsp_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='ancestor_task',
            field=models.ForeignKey(help_text='The task within which the subprocess should be executed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_workflows', to='processes.Task'),
        ),
    ]
