# Generated by Django 2.2 on 2024-08-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0208_migrate_terminated_wf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='wf_name_template_is_active',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.IntegerField(choices=[(0, 'Workflow in work'), (1, 'Workflow done'), (3, 'Workflow delayed')], default=0),
        ),
    ]
