# Generated by Django 2.2 on 2024-08-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0209_auto_20240813_2033'),
    ]

    operations = [
        migrations.RunSQL("""
        UPDATE processes_systemtemplate
          SET template = template || jsonb_build_object('wf_name_template', template->'name')
        WHERE is_deleted IS FALSE
        """)
    ]
