# Generated by Django 2.2 on 2024-09-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0213_auto_20240919_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicate',
            name='field',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='field_type',
            field=models.CharField(choices=[('kickoff', 'kickoff'), ('task', 'task'), ('string', 'string'), ('text', 'text'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('date', 'date'), ('url', 'url'), ('dropdown', 'dropdown'), ('file', 'file'), ('user', 'user')], max_length=20),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equal'), ('not_equals', 'Not equal'), ('exists', 'Exists'), ('not_exists', 'Not exists'), ('contains', 'Contains'), ('not_contains', 'Not contains'), ('more_than', 'More than'), ('less_than', 'Less than'), ('completed', 'completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='predicatetemplate',
            name='field',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='predicatetemplate',
            name='field_type',
            field=models.CharField(choices=[('kickoff', 'kickoff'), ('task', 'task'), ('string', 'string'), ('text', 'text'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('date', 'date'), ('url', 'url'), ('dropdown', 'dropdown'), ('file', 'file'), ('user', 'user')], max_length=20),
        ),
        migrations.AlterField(
            model_name='predicatetemplate',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equal'), ('not_equals', 'Not equal'), ('exists', 'Exists'), ('not_exists', 'Not exists'), ('contains', 'Contains'), ('not_contains', 'Not contains'), ('more_than', 'More than'), ('less_than', 'Less than'), ('completed', 'completed')], max_length=30),
        ),
    ]
