# Generated by Django 2.2 on 2024-09-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0214_auto_20240919_1406'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE processes_taskfield
            SET value = EXTRACT(EPOCH FROM value::date)
            WHERE type = 'date' 
            AND value <> '' 
            AND value LIKE '%/%/%';
        """),
    ]
