# Generated by Django 2.2 on 2024-10-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0214_auto_20240919_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='taskfield',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='fieldselection',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='kickoffvalue',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='rawperformer',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='template_id',
        ),
    ]
