# Generated by Django 2.2 on 2024-10-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0215_migrate_output_fields_type_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawperformer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserGroup'),
        ),
        migrations.AddField(
            model_name='rawperformertemplate',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserGroup'),
        ),
    ]
