# Generated by Django 2.2 on 2024-09-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0217_remove_tasks_count'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE processes_workflowevent
            SET task_json = jsonb_set(
                task_json,
                '{output}',
                (
                    SELECT jsonb_agg(
                        CASE
                            WHEN elem->>'type' = 'date'
                             AND elem->>'value' IS NOT NULL 
                             AND elem->>'value' <> '' 
                             AND elem->>'value' LIKE '%/%/%'
                            THEN jsonb_set(elem, '{value}', to_jsonb(EXTRACT(EPOCH FROM (elem->>'value')::date)))
                            ELSE elem
                        END
                    )
                    FROM jsonb_array_elements(task_json->'output') AS elem
                )
            )
            WHERE task_json IS NOT NULL
            AND task_json->'output' IS NOT NULL
            AND jsonb_typeof(task_json->'output') = 'array';
        """),

        migrations.RunSQL("""
            UPDATE processes_predicatetemplate
            SET value = EXTRACT(EPOCH FROM value::date)
            WHERE value IS NOT NULL
            AND value <> ''
            AND field_type = 'date';
        """),

        migrations.RunSQL("""
            UPDATE processes_predicate
            SET value = EXTRACT(EPOCH FROM value::date)
            WHERE value IS NOT NULL
            AND value <> ''
            AND field_type = 'date';
        """),
    ]
