# Generated by Django 2.2 on 2024-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0218_migrate_output_fields_workflowevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfield',
            name='markdown_value',
            field=models.TextField(blank=True, help_text='Contains markdown representation', null=True),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='value',
            field=models.TextField(blank=True, help_text='Human readable value'),
        ),
    ]
