# Generated by Django 2.2 on 2025-02-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0223_migrate_template_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='revert_task',
            field=models.CharField(blank=True, help_text='Api name task to revert', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='revert_task',
            field=models.CharField(blank=True, help_text='Api name task to revert', max_length=255, null=True),
        ),
    ]
