# Generated by Django 2.2 on 2025-01-28 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0130_add_user_groups'),
        ('processes', '0224_add_revert_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskperformer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserGroup'),
        ),
        migrations.AddField(
            model_name='taskperformer',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('group', 'group'), ('workflow_starter', 'workflow_starter'), ('field', 'field')], default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='target_group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskperformer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='type',
            field=models.IntegerField(choices=[(0, 'Workflow started'), (1, 'Workflow completed'), (2, 'Task started'), (3, 'Task completed'), (4, 'Task reverted'), (9, 'Task skipped'), (5, 'New comment'), (6, 'Workflow ended'), (7, 'Workflow snoozed from template'), (17, 'Workflow snoozed'), (8, 'Workflow reverted'), (10, 'Workflow ended by condition'), (11, 'Workflow is urgent'), (12, 'Workflow is not urgent'), (13, 'Task skipped as no performers were assigned'), (14, 'Performer added to task'), (15, 'Performer deleted from task'), (16, 'Workflow resumed'), (18, 'Due date changed'), (14, 'Performer group added to task'), (15, 'Performer group deleted from task')], verbose_name='type'),
        ),
    ]
