# Generated by Django 2.2 on 2025-01-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    # Migrate performers list ids to list objects

    dependencies = [
        ('processes', '0227_add_task_status'),
    ]

    operations = [
        migrations.RunSQL(
            """ UPDATE processes_workflowevent
                SET task_json = jsonb_set(
                        task_json,
                        '{performers}',
                        (
                            SELECT jsonb_agg(
                                CASE
                                    WHEN jsonb_typeof(elem) = 'object' THEN elem
                                    ELSE jsonb_build_object('source_id', elem, 'type', 'user')
                                END
                            )
                            FROM jsonb_array_elements(task_json->'performers') AS elem
                            
                        )
                    )
                WHERE task_json IS NOT NULL
                AND task_json->'performers' IS NOT NULL
                AND jsonb_typeof(task_json->'performers') = 'array'
            """
        )
    ]
