# Generated by Django 2.2 on 2025-04-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0228_migrate_performers_fmt_for_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateowner',
            options={'ordering': ['type', 'id']},
        ),
        migrations.AddField(
            model_name='taskfield',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown'), ('file', 'File'), ('user', 'User'), ('number', 'Number')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed'), ('snoozed', 'snoozed'), ('skipped', 'skipped')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown'), ('file', 'File'), ('user', 'User'), ('number', 'Number')], max_length=10),
        ),
    ]
