# Generated by Django 2.2.7 on 2019-12-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default comment'), (1, 'Return task')], default=0),
        ),
    ]
