# Generated by Django 2.2.9 on 2020-01-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_auto_20200113_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='date_started',
            field=models.DateTimeField(null=True),
        ),
    ]
