# Generated by Django 2.2.12 on 2020-04-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0018_auto_20200406_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_by_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskworkflow',
            name='complete_by_all',
            field=models.BooleanField(default=False),
        ),
    ]
