# Generated by Django 2.2.12 on 2020-04-24 23:43

from django.db import migrations


def create_througth_relations(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0020_taskcomplete'),
    ]

    operations = [
        migrations.RunPython(create_througth_relations, reverse_code=migrations.RunPython.noop)
    ]
