# Generated by Django 2.2.12 on 2020-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0023_auto_20200505_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickofffieldtemplate',
            name='api_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='kickofffieldtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
