# Generated by Django 2.2.12 on 2020-05-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0025_auto_20200507_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kickofffieldtemplate',
            name='workflow',
        ),
        migrations.AddField(
            model_name='kickoff',
            name='workflow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kickoff', to='processes.Workflow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kickofffieldtemplate',
            name='kickoff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.Kickoff'),
        ),
    ]
