# Generated by Django 2.2.13 on 2020-06-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0031_auto_20200608_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='type',
            field=models.CharField(choices=[('custom', 'custom'), ('generic', 'generic'), ('generic_clone', 'generic clone')], default='custom', max_length=16),
        ),
    ]
