# Generated by Django 2.2.13 on 2020-07-01 11:21

from django.db import migrations


def add_description_template(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0038_task_description_template'),
    ]

    operations = [
        migrations.RunPython(add_description_template, reverse_code=migrations.RunPython.noop)
    ]
