# Generated by Django 2.2.16 on 2020-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0064_auto_20200915_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='taskworkflow',
            name='url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
