# Generated by Django 2.2.16 on 2020-09-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0068_merge_20200917_1337'),
        ('processes', '0068_merge_20200917_1429'),
    ]

    operations = [
    ]
