# Generated by Django 2.2.16 on 2020-09-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0075_auto_20200929_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='processes.Comment'),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='processes.TaskField'),
        ),
    ]
