# Generated by Django 2.2.16 on 2020-11-02 13:16

from django.db import migrations


def templates_from_onboarding_to_admin(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0086_auto_20201102_1316'),
    ]

    operations = [
        migrations.RunPython(templates_from_onboarding_to_admin, reverse_code=migrations.RunPython.noop)
    ]
