# Generated by Django 2.2.16 on 2020-11-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0094_auto_20201116_1404'),
        ('processes', '0094_merge_20201116_0818'),
    ]

    operations = [
    ]
