# Generated by Django 2.2.16 on 2020-11-27 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0096_taskworkflow_is_starter_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process', to=settings.AUTH_USER_MODEL),
        ),
    ]
