# Generated by Django 2.2.13 on 2020-07-01 11:21

from django.db import migrations


def set_account_for_task(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0096_auto_20201127_1225'),
    ]

    operations = [
        migrations.RunPython(set_account_for_task, reverse_code=migrations.RunPython.noop)
    ]
