# Generated by Django 2.2.16 on 2020-11-25 11:29

from django.db import migrations


def update_workflow_types(apps, schema_editor):
    pass


def undo_update_workflow_types(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0096_auto_20201125_1128'),
    ]

    operations = [
        migrations.RunPython(update_workflow_types, reverse_code=undo_update_workflow_types)
    ]
