# Generated by Django 2.2.17 on 2020-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0101_fill_name_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name_template',
            field=models.CharField(max_length=140),
        ),
    ]
