# Generated by Django 2.2.17 on 2021-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0104_auto_20210131_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplate',
            name='type',
            field=models.CharField(choices=[('generic', 'Generic Workflows'), ('owner_onboarding', 'Account Owners Onboarding Workflow'), ('invited_onboarding_admin', 'Invited Admin Users Onboarding Workflow'), ('invited_onboarding_regular', 'Invited Non-Admin Users Onboarding Workflow'), ('activated_template', 'Activated Template')], default='generic', max_length=48),
        ),
    ]
