# Generated by Django 2.2.17 on 2021-03-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0109_auto_20210319_1200'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE processes_fieldtemplateselection fts SET api_name = collection.api_name
            FROM (
              SELECT id, concat('selection-', substr(md5(random()::text), 0, 10)) as api_name
              FROM processes_fieldtemplateselection WHERE is_deleted IS FALSE
            ) collection
            WHERE fts.id = collection.id;

            UPDATE processes_fieldselection fs SET api_name = fts.api_name
            FROM processes_fieldtemplateselection fts
            WHERE fs.template_id = fts.id AND
              fs.is_deleted IS FALSE AND
              fts.is_deleted IS FALSE
            """,
            reverse_sql="""
                UPDATE processes_fieldtemplateselection SET api_name = NULL;
                UPDATE processes_fieldselection SET api_name = NULL;
            """
        )
    ]
