# Generated by Django 2.2.17 on 2021-04-26 07:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0121_create_kickoff'),
    ]

    operations = [
        migrations.RunSQL(sql="""
          DELETE FROM processes_taskresponsible a
          USING processes_taskresponsible b
          WHERE a.id > b.id AND a.user_id = b.user_id AND a.task_id = b.task_id;
        """),
        migrations.AlterUniqueTogether(
            name='taskresponsible',
            unique_together={('user', 'task')},
        ),
    ]
