# Generated by Django 2.2.17 on 2021-06-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0134_fill_template_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditiontemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='processes.Template'),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.Template'),
        ),
        migrations.AlterField(
            model_name='fieldtemplateselection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='processes.Template'),
        ),
        migrations.AlterField(
            model_name='predicatetemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicates', to='processes.Template'),
        ),
        migrations.AlterField(
            model_name='ruletemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='processes.Template'),
        ),
    ]
