# Generated by Django 2.2.24 on 2021-06-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0137_template_public_success_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileattachment',
            old_name='process',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='process',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='kickoffvalue',
            old_name='process',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='process',
            new_name='workflow',
        ),
        migrations.RenameModel(
            old_name='Process',
            new_name='Workflow',
        ),
    ]
