# Generated by Django 2.2.24 on 2021-09-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0143_workflow_date_completed'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                WITH 
                orphan_workflow AS (
                    SELECT
                      FALSE AS is_deleted, 
                      pk.description,
                      pw.account_id, 
                      pw.id AS workflow_id, 
                      pk.id AS template_id
                    FROM processes_workflow pw
                      LEFT JOIN processes_kickoffvalue pkv ON pw.id = pkv.workflow_id
                      LEFT JOIN processes_kickoff pk ON pk.template_id=pw.template_id AND pk.is_deleted is FALSE
                    WHERE pw.is_deleted is FALSE AND pkv.id is NULL
                )
                
                INSERT INTO processes_kickoffvalue (is_deleted, description, account_id, workflow_id, template_id)
                SELECT is_deleted, description, account_id, workflow_id, template_id
                FROM orphan_workflow
            """,
            reverse_sql=""
        )
    ]
