# Generated by Django 2.2.24 on 2021-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0148_auto_20211011_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
