# Generated by Django 2.2.28 on 2023-01-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0176_remove_onboarding_tempaltes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemworkflowkickoffdata',
            options={'ordering': ('user_role', 'order'), 'verbose_name': 'System workflow kickoff', 'verbose_name_plural': 'System workflow kickoff'},
        ),
        migrations.AddField(
            model_name='template',
            name='system_template_id',
            field=models.IntegerField(null=True),
        ),
    ]
