# Generated by Django 2.2.26 on 2023-03-16 09:51

from django.db import migrations, models
import django.db.models.deletion
import pneumatic_backend.generics.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0179_workflow_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDueDateTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_name', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('rule', models.CharField(choices=[('before field', 'before field'), ('after field', 'after field'), ('after workflow started', 'after workflow started'), ('after task started', 'after task started'), ('after task completed', 'after task completed')], max_length=100)),
                ('source_id', models.CharField(max_length=200, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_due_date', to='processes.TaskTemplate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_due_dates', to='processes.Template')),
            ],
            options={
                'ordering': ('pk',),
            },
            bases=(pneumatic_backend.generics.mixins.models.SoftDeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='rawduedatetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('template', 'api_name'), name='processes_rawduedatetemplate_template_api_name_unique'),
        ),
    ]
