# Generated by Django 2.2.28 on 2023-03-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0182_task_api_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawduedate',
            name='template_id',
        ),
    ]
