# Generated by Django 2.2.28 on 2023-03-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0185_task_due_date_directly_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawduedate',
            name='duration_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawduedatetemplate',
            name='duration_months',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
