# Generated by Django 2.2 on 2024-01-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0199_auto_20240124_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowevent',
            name='clear_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
