# Generated by Django 2.2 on 2025-01-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0226_remove_template_template_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('snoozed', 'snoozed'), ('skipped', 'skipped')], default='pending', max_length=50),
        ),
        migrations.RunSQL(
            """
            UPDATE processes_task
            SET status = (
              SELECT CASE
                WHEN (
                  pt.is_completed IS FALSE AND
                  pt.date_started IS NULL AND
                  pt.is_skipped IS FALSE
                ) THEN 'pending'
                WHEN (
                  pt.is_completed IS FALSE AND
                  pt.date_started IS NOT NULL AND
                  pt.is_skipped IS FALSE AND
                  workflow.current_task = pt.number
                ) THEN 'active'
                WHEN is_completed IS TRUE THEN 'completed'
                WHEN (
                  pt.is_completed IS FALSE AND
                  pt.date_started IS NOT NULL AND
                  pt.is_skipped IS FALSE AND
                  workflow.current_task = pt.number AND
                  workflow.status = 3
                ) THEN 'snoozed'
                WHEN (
                  pt.is_skipped IS TRUE
                  OR (
                    pt.is_completed IS FALSE AND
                    pt.date_started IS NOT NULL AND
                    pt.is_skipped IS FALSE AND
                    workflow.current_task != pt.number AND
                    workflow.status = 1
                  )
                ) THEN 'skipped'
                WHEN (
                    pt.is_deleted IS TRUE AND
                    pt.is_completed IS FALSE AND
                    pt.date_started IS NOT NULL AND
                    pt.is_skipped IS FALSE
                ) THEN 'pending'
                WHEN (
                    pt.is_deleted IS FALSE AND
                    pt.is_completed IS FALSE AND
                    pt.date_started IS NOT NULL AND
                    pt.is_skipped IS FALSE AND
                    workflow.current_task != pt.number
                ) THEN 'pending'
              END
              FROM processes_task pt
              INNER JOIN processes_workflow workflow
                ON workflow.id = pt.workflow_id
              WHERE pt.id = processes_task.id
            )
            """
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='is_completed_deprecated',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_skipped',
            new_name='is_skipped_deprecated',
        ),
    ]
