        # Django admin files
        location /static/ {
            alias /tmp/backend-staticfiles/;
        }
        location /robots.txt {
            alias /var/www/robots.txt;
        }
        location = /502.html {
            alias /var/www/html/502.html;
        }
