# Generated by Django 2.2 on 2024-12-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_accountevent_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountevent',
            old_name='body',
            new_name='request_data',
        ),
        migrations.RenameField(
            model_name='accountevent',
            old_name='error',
            new_name='response_data',
        ),
    ]
